feat(CockroachDB)
observIQ/bindplane-op pull request #1000
Opened 2023-04-28 19:44 UTC by BominRahmani

### Proposed Change

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-04-28 19:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/observIQ/bindplane-op?pullRequest=1000) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/observIQ/bindplane-op?pullRequest=1000) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/observIQ/bindplane-op?pullRequest=1000) it.</sub>

2023-05-01 13:11 UTC, jsirianni commented
Does this source type depend on a collector plugin pull request? If so, can you link it here? Thanks!

2023-05-01 13:25 UTC, jsirianni reviewed
Looks great, have not tried it out yet but will when the PR is finalized. Left a few comments.

2023-05-01 13:25 UTC, jsirianni commented on resources/source-types/cockroach.yaml
> +    default: 8080
Is there documentation on this port? If so, can we link it using [this pattern](https://github.com/observIQ/bindplane-op/blob/feature/cockroachdb-source/resources/destination-types/grafana_cloud.yaml#L14)?

2023-05-01 13:25 UTC, jsirianni commented on resources/source-types/cockroach.yaml
> +    default: 8080
Similarly, lets use the external documentation "read more" on any parameter which has associated documentation, like username / password or information on each log type. 

This is a newer feature, so you may not have seen it in previous source types.

2023-05-01 13:25 UTC, jsirianni commented on resources/source-types/cockroach.yaml
> +  - name: enable_health_log
nit, lets be consistent with spacing between each param.
```suggestion
    default: true
  
  - name: enable_health_log
```

2023-05-01 13:25 UTC, jsirianni commented on resources/source-types/cockroach.yaml
> +      - resourcedetection:
We should use this processor in the metrics pipeline as well.

2023-05-03 18:08 UTC, BominRahmani commented
> Does this source type depend on a collector plugin pull request? If so, can you link it here? Thanks!

Hey Joe! Thanks for the comments. I took care of most of them.
Here is the link to the PR this is dependent on. https://github.com/observIQ/observiq-otel-collector/pull/1039
I will also update the description of this PR to include this link!

2023-06-14 18:36 UTC, jsirianni requested changes

2023-06-14 18:36 UTC, jsirianni commented on resources/source-types/cockroach.yaml
> +        value: true
Lets follow [this](https://github.com/observIQ/bindplane-op/blob/main/resources/source-types/nginx.yaml#L52) pattern for TLS parameters.
- TLS options should be gated behind an "enable tls" toggle
- Cert file and key file options should make it clear that they are for mutual tls

2023-06-14 18:36 UTC, jsirianni commented on resources/source-types/cockroach.yaml
> +  - name: server_name
The read more link indicates that this is a TLS option. It should be nested under the "enable tls" toggle mentioned in my previous comment. We can probably remove the "advanced: true" option here.

2023-06-14 18:36 UTC, jsirianni commented on resources/source-types/cockroach.yaml
> +  - name: insecure_skip_verify
This should be nested under the "enable tls" toggle mentioned in my previous comment. We can probably remove the "advanced: true" option here.

2023-06-15 16:00 UTC, BominRahmani commented on resources/source-types/cockroach.yaml
> +  - name: server_name
I kept the advanedConfig: true to keep it bundled with the TLS option, since the tls option seems to fall under an advancedConfig: true in the pattern you linked as well as in the elastic search.

2023-06-15 16:00 UTC, BominRahmani commented on resources/source-types/cockroach.yaml
> +  - name: insecure_skip_verify
I kept the advanedConfig: true to keep it bundled with the TLS option, since the tls option seems to fall under an advancedConfig: true in the pattern you linked as well as in the elastic search.

2023-06-15 18:04 UTC, jsirianni reviewed
I think this looks good, left one more comment.

2023-06-15 18:04 UTC, jsirianni commented on resources/source-types/cockroach.yaml
> +  - name: collection_interval
Lets re-arrange the params so all TLS options are grouped. Right now, collection interval sits between server name and skip verification.

![Screenshot from 2023-06-15 13-59-52](https://github.com/observIQ/bindplane-op/assets/23043836/64acb55f-694f-4dc2-bc34-18d0abeeb6d5)

2023-06-15 18:15 UTC, BominRahmani commented on resources/source-types/cockroach.yaml
> +  - name: collection_interval
<img width="885" alt="image" src="https://github.com/observIQ/bindplane-op/assets/38274348/a3d6b8fe-142b-435e-bf70-79a5f1eccde9">

2023-06-16 14:37 UTC, BinaryFissionGames commented on resources/source-types/cockroach.yaml
> +    description: File path for CA certification file for CockroachDB (only needed if you have a secure cluster)
```suggestion
    description: File path for CA certification file for CockroachDB (only needed if you have a secure cluster).
```

2023-06-16 14:37 UTC, BinaryFissionGames commented on resources/source-types/cockroach.yaml
> +    description: Name of server
```suggestion
    description: The name of the server.
```

2023-06-16 14:37 UTC, BinaryFissionGames commented on resources/source-types/cockroach.yaml
> +    description: Enable to collect health logs
Could we add a period to the end of all these descriptions, just so they are consistent?

2023-06-16 14:37 UTC, BinaryFissionGames commented on resources/source-types/cockroach.yaml
> +            server_name: {{ .server_name | quote}}
We should only fill these parameters in if `enable_tls` is true, otherwise if you fill in the tls parameters and uncheck the tls enable, tls still applies.

2023-06-19 15:27 UTC, BominRahmani commented on resources/source-types/cockroach.yaml
> +    description: The password to use when connecting to CockroachDB. TLS must be configured in advance if this field is set.
Glad to hear it!

2023-06-19 17:29 UTC, BinaryFissionGames approved these changes

2023-06-21 11:29 UTC, merged