feat(ui): Resource display naming
observIQ/bindplane-op pull request #1099
Opened 2023-05-22 17:25 UTC by shazlehu

### Proposed Change

Provides ability to add a display name to sources and processors per https://app.vivifyscrum.com/boards/114813/sprint-backlog/375847/BPOP-860

This PR adds the ability to display, but not edit.  To test, add displayName attribute to configuration resources, as in this example configuration: https://drive.google.com/file/d/1IXioT_aZkIrFvD9BYI0Ej817cr0agutH/view?usp=share_link

`bindplanectl apply -f test.yaml`

Source cards and processor lists should now include displayName

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-05-24 15:41 UTC, dsvanlani requested changes

2023-05-24 15:41 UTC, dsvanlani commented on ui/src/components/Cards/ResourceDestinationCard.tsx
> +                    ml={-1}
Can we just include the margin-left in the .scss file since we have a class on this component already?
```suggestion
```

2023-05-24 15:41 UTC, dsvanlani commented on ui/src/components/Cards/InlineSourceCard.tsx
> +                  {/* TODO: horizontal line separating displayName from Paused */}
Do we need to do this?

2023-05-24 15:41 UTC, dsvanlani commented on ui/src/components/PipelineGraph/pipeline-graph.module.scss
> +  max-width: 2000px;
Was this requested?

2023-05-24 15:41 UTC, dsvanlani commented on ui/src/components/ResourceDialog/ProcessorsDialog/InlineProcessorLabel.tsx
> +          <Typography fontWeight={900}>{data?.processorType?.metadata.displayName}</Typography>
I dont think we actually have fontWeight 900, just 300,400,600, for nunito sans.  We import these in the `index.html` file for reference.
```suggestion
          <Typography fontWeight={600}>{data?.processorType?.metadata.displayName}</Typography>
```

2023-05-24 15:41 UTC, dsvanlani commented on ui/src/components/ResourceDialog/ProcessorsDialog/ViewOnlyProcessorLabel.tsx
> +          <Typography fontWeight={900}>{data?.processorType?.metadata.displayName}</Typography>
```suggestion
          <Typography fontWeight={600}>{data?.processorType?.metadata.displayName}</Typography>
```

2023-05-24 15:41 UTC, dsvanlani commented on ui/src/components/ResourceConfigForm/ResourceConfigurationView.tsx
> +  includeDescriptionField?: boolean;
Does it? This isn't used anywhere

2023-05-24 15:43 UTC, dsvanlani commented
I like the new shape of the cards - but I think the icons should be more stationary on the left hand side of the card, and not move depending on the length of the source name/display name text

![image](https://github.com/observIQ/bindplane-op/assets/64915094/23603059-948b-4648-a123-ecb46cc96c4b)

2023-05-24 16:15 UTC, shazlehu commented
> I like the new shape of the cards - but I think the icons should be more stationary on the left hand side of the card, and not 
> move depending on the length of the source name/display name text

I went back and forth on this one. Guess it's a topic for ticket review?

2023-05-24 17:34 UTC, jmwilliams89 commented
> > I like the new shape of the cards - but I think the icons should be more stationary on the left hand side of the card, and not
> > move depending on the length of the source name/display name text
> 
> I went back and forth on this one. Guess it's a topic for ticket review?

I agree with Dave on this one. I think these should be left aligned at all times.

2023-05-30 18:31 UTC, BinaryFissionGames commented on ui/src/components/ResourceDialog/ProcessorsDialog/InlineProcessorLabel.tsx
>          </Stack>
This is more a design question, but is there any way we might be able to put some separator here? At a glance it the font weight difference wasn't super apparent to me to differentiate the processor type vs the processor name.

2023-05-31 17:50 UTC, shazlehu commented on ui/src/components/ResourceDialog/ProcessorsDialog/InlineProcessorLabel.tsx
>          </Stack>
Added a colon, per Ryan's suggestion

2023-05-31 17:53 UTC, BinaryFissionGames approved these changes

2023-05-31 20:28 UTC, merged