feat(ui): Resource display naming editing
observIQ/bindplane-op pull request #1107
Opened 2023-05-23 16:40 UTC by shazlehu

### Proposed Change
Allows the editing of source and processor display names

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-05-24 20:21 UTC, dsvanlani commented on ui/src/components/ResourceConfigForm/ResourceConfigurationView.tsx
> +  // The display name of the Source or Destination
```suggestion
  // The display name of the Source or Processor
```

2023-05-24 20:41 UTC, dsvanlani requested changes
Working pretty well.  My big things:

1. I think we should limit the length of display Names to be like 20 characters or something.
2. Also was not able to set the display name when creating a processor for the first time. (commented out code)
3. We need to move the displayName field above "Configure" in the processor form.
3. I'd like to see the prop names change for ResourceConfigureView to something more intuitive.

2023-05-24 20:41 UTC, dsvanlani commented on ui/src/components/ResourceConfigForm/ResourceConfigurationView.tsx
> +  existingDisplayName?: string;
Ok the prop names are confusing here and I think its a good chance to rename them.

Could we rename `displayName` to be `resourceTypeDisplayName` and rename `existingDisplayName` to `displayName`?

2023-05-24 20:41 UTC, dsvanlani commented on ui/src/components/ResourceConfigForm/ParameterInput/ResourceDisplayNameInput.tsx
> +      }
Whats going on here?  Seems to be just fine like this.
```suggestion
      helperText="Additional description for the resource."
```

Also I think it could just be "A friendly name for the resource"

2023-05-24 20:41 UTC, dsvanlani commented on ui/src/components/ResourceDialog/ProcessorsDialog/ProcessorForm.tsx
> +        <Grid item xs={6}>
Can we move this above `Configure` so it stayes consistent with the Source creation?

2023-05-24 20:41 UTC, dsvanlani commented on ui/src/components/ResourceDialog/ProcessorsDialog/ProcessorForm.tsx
> +              {}
We're going to want this. We're unable to set the display name when creating now.
```suggestion
              setFormValues((prev) => ({ ...prev, name: v }))
              
```

2023-05-24 20:41 UTC, dsvanlani commented on ui/src/components/ResourceDialog/ProcessorsDialog/ProcessorDialog.test.tsx
> +      target: { value: "Awesome Processor" },
I don't think this is changing the name? Its already set as Awesome Processor?

2023-05-24 20:41 UTC, dsvanlani commented on ui/src/components/ResourceDialog/ProcessorsDialog/ProcessorDialog.test.tsx
Here we should actually check for the new value.
```tsx
await screen.findByText("Edited Awesome Processor Name")
```

2023-05-24 20:41 UTC, dsvanlani commented on ui/src/components/ResourceConfigForm/init-form-values.ts
> +  defaults.displayName = displayName;
Can we just do this above?

```
let defaults: FormValues = {
    displayName,
}
```

2023-05-24 20:41 UTC, dsvanlani requested changes
Working pretty well.  My big things:

1. I think we should limit the length of display Names to be like 20 characters or something.
2. Also was not able to set the display name when creating a processor for the first time. (commented out code)
3. We need to move the displayName field above "Configure" in the processor form.
3. I'd like to see the prop names change for ResourceConfigureView to something more intuitive.

2023-05-24 20:50 UTC, shazlehu commented on ui/src/components/ResourceConfigForm/ParameterInput/ResourceDisplayNameInput.tsx
> +      }
That's copy pasta from ResourceNameParamInput

2023-05-24 20:55 UTC, shazlehu commented on ui/src/components/ResourceConfigForm/ResourceConfigurationView.tsx
> +  existingDisplayName?: string;
It's not a resource type display name, it's a display name for an  inline source or processor. So maybe `inlineResourceDisplayName`?

2023-05-24 21:07 UTC, dsvanlani commented on ui/src/components/ResourceConfigForm/ParameterInput/ResourceDisplayNameInput.tsx
> +      }
I think thats because that has error validation.

2023-05-24 21:49 UTC, shazlehu commented on ui/src/components/ResourceDialog/ProcessorsDialog/ProcessorDialog.test.tsx
> +      target: { value: "Awesome Processor" },
I don't think it's set until here

2023-05-24 21:52 UTC, shazlehu commented on ui/src/components/ResourceDialog/ProcessorsDialog/ProcessorDialog.test.tsx
> +      target: { value: "Awesome Processor" },
I think it's set here. The mock value is what we expect the graphql parameter to be.

2023-05-25 00:23 UTC, dsvanlani commented on ui/src/components/ResourceConfigForm/ResourceConfigurationView.tsx
> +  existingDisplayName?: string;
I think `inlineResourceDisplayName` is better if you want to do that.

2023-05-25 00:31 UTC, shazlehu commented on ui/src/components/ResourceConfigForm/ResourceConfigurationView.tsx
> +  existingDisplayName?: string;
Actually, you're right, these names are confusing... displayName on the props should be resourceTypeDisplayName.

2023-05-25 01:13 UTC, shazlehu commented on ui/src/components/ResourceConfigForm/ResourceConfigurationView.tsx
> +  existingDisplayName?: string;
Change made

2023-05-30 18:33 UTC, BinaryFissionGames commented on ui/src/components/Cards/InlineSourceCard.tsx
> +                      <Typography fontWeight={600} fontSize={12}>
Seems like this text should be centered?
```suggestion
                      <Typography fontWeight={600} fontSize={12} textAlign="center">
```
![Screen Shot 2023-05-30 at 2 25 51 PM](https://github.com/observIQ/bindplane-op/assets/10042942/a62cbd64-3e5d-45ca-90ff-5560cb18a8a3)
vs
![Screen Shot 2023-05-30 at 2 25 32 PM](https://github.com/observIQ/bindplane-op/assets/10042942/86930375-7a6a-4cf1-8903-ab5951728171)

2023-05-30 18:33 UTC, BinaryFissionGames commented on ui/src/components/Cards/InlineSourceCard.tsx
>                          {truncateLabel(source?.displayName, 20)}
This only truncates the name if it doesn't have spaces. I think it would be better if it still truncated display names with spaces.

2023-05-30 20:45 UTC, shazlehu commented on ui/src/components/Cards/InlineSourceCard.tsx
>                          {truncateLabel(source?.displayName, 20)}
Is superlongwordthatcan'tfit a real word? We skip truncation for phrases with spaces since word wrapping applies.

2023-05-30 20:47 UTC, shazlehu commented on ui/src/components/Cards/InlineSourceCard.tsx
> +                      <Typography fontWeight={600} fontSize={12}>
Guess this is q question for Ryan -- I think it's changed back and forth more than once already!

2023-05-31 17:13 UTC, BinaryFissionGames commented on ui/src/components/Cards/InlineSourceCard.tsx
> +                      <Typography fontWeight={600} fontSize={12}>
Product decision is to leave as is

2023-05-31 17:20 UTC, BinaryFissionGames commented on ui/src/components/Cards/InlineSourceCard.tsx
>                          {truncateLabel(source?.displayName, 20)}
Input is limited to 40 characters now.

2023-05-31 17:20 UTC, BinaryFissionGames approved these changes

2023-05-31 17:51 UTC, merged