feat(added read more option for int fields)
observIQ/bindplane-op pull request #1191
Opened 2023-06-14 15:49 UTC by BominRahmani

### Proposed Change

Added an option to see the read more option with a link on int params. Previously would not work with them.
<img width="450" alt="image" src="https://github.com/observIQ/bindplane-op/assets/38274348/dafa672b-298e-43cb-a1f2-68ef97e50cd3">

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-06-14 17:22 UTC, antonblock requested changes

2023-06-14 17:22 UTC, antonblock commented on ui/src/components/ResourceConfigForm/ParameterInput/IntParamInput.tsx
> +import { FormHelperText, TextField, Stack } from "@mui/material";
```suggestion
import { FormHelperText, Stack, TextField } from "@mui/material";
```

2023-06-14 17:22 UTC, antonblock commented on ui/src/components/ResourceConfigForm/ParameterInput/IntParamInput.tsx
> +                <a href={d.url} rel="noreferrer" target="_blank">
```suggestion
                <a href={d.url} rel="noreferrer" target="_blank" key={d.url}>
```
If each item doesn't have a key we get a console error (https://github.com/observIQ/bindplane-op/pull/1175)

2023-06-14 17:53 UTC, antonblock approved these changes

2023-06-15 12:03 UTC, cpheps approved these changes

2023-06-16 20:17 UTC, merged