feat: Parameter types `map`, `yaml`, and `multi-enum`
observIQ/bindplane-op pull request #122
Opened 2022-07-19 14:24 UTC by dsvanlani

### Proposed Change
For upcoming features related to processors and metric toggling we've added new Parameter Types for our Resource Configuration Form.

The list of possible types has been expanded to include `map`, `yaml` and `multi-enum`:

```go
const (
	stringType    = "string"
	boolType      = "bool"
	intType       = "int"
	stringsType   = "strings"
	enumType      = "enum"
	multiEnumType = "multi-enum"
	yamlType      = "yaml"
	mapType       = "map"
)
```

I've added a contrived test resource `model/testfiles/sourcetype-experimental-parameters.yaml` to show these in action.

### To Test

Add the source type with experimental values:

```sh
go run cmd/bindplane/main.go apply -f model/testfiles/sourcetype-experimental-parameters.yaml
```

And you can add it from anywhere you add a source:
![image](https://user-images.githubusercontent.com/64915094/179774369-95da7cc9-9639-432c-b819-c76fddd9ccda.png)

showing our new parameter types:
![image](https://user-images.githubusercontent.com/64915094/179774458-a26728af-c2ec-46fc-8d4b-e22a0efcb254.png)

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-07-27 14:11 UTC, andykellr commented on model/parameter.go
> +		// TODO
```suggestion
```

2022-07-27 17:38 UTC, andykellr approved these changes

2022-07-27 17:45 UTC, jsirianni requested changes
I am having a couple issues with yaml and map types. Talking to Dave offline about it.

2022-07-28 02:04 UTC, andykellr approved these changes

2022-07-28 02:04 UTC, andykellr commented
I didn't mean to approve again. Let's make sure everything's good for @jsirianni

2022-07-28 18:04 UTC, jsirianni approved these changes

2022-07-28 18:53 UTC, merged