fix: Button audit
observIQ/bindplane-op pull request #1226
Opened 2023-06-23 17:57 UTC by shazlehu

### Proposed Change

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-06-25 01:35 UTC, andykellr approved these changes

2023-06-26 17:54 UTC, dsvanlani requested changes

2023-06-26 17:54 UTC, dsvanlani commented on ui/src/components/ManageConfigForm/index.tsx
>                    variant="contained"
I think this would be the secondary action, and therefore outlined.  Also can we make the `Cancel` button a text button as its the tertiary action?

```suggestion
                  variant="outlined"
```

2023-06-26 17:54 UTC, dsvanlani commented on ui/src/components/BuildRolloutDialog/BuildRolloutDialog.tsx
> +                color="success"
I think that should be the primary brand color.

Can @jmwilliams89 or @ryancgoins weigh in here?

2023-06-26 19:59 UTC, jmwilliams89 commented on ui/src/components/BuildRolloutDialog/BuildRolloutDialog.tsx
> +                color="success"
Yeah, that should be the primary color.

2023-06-26 20:05 UTC, shazlehu commented on ui/src/components/BuildRolloutDialog/BuildRolloutDialog.tsx
> +                color="success"
I remember a groundswell of support for "success" green

2023-06-28 19:15 UTC, closed without merging

2023-06-29 13:50 UTC, shazlehu commented on ui/src/components/BuildRolloutDialog/BuildRolloutDialog.tsx
> +                color="success"
I surrender

2023-06-29 13:55 UTC, dsvanlani approved these changes