fix: Source icon updates
observIQ/bindplane-op pull request #1228
Opened 2023-06-23 20:46 UTC by kuiperda

### Proposed Change
Changes:
- Splunk logo replaced
- Journald logo replaced
- Cisco Meraki logo changed to generic Cisco logo (and Meraki logo removed)
- File, Custom, CEV, CSV, WC3 logos standardized (font is Nunito Sans 7pt Condensed - Bold Condensed)
- Drop shadow removed from topology graph lines (Mike requested this)

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-06-28 13:50 UTC, dsvanlani requested changes

2023-06-28 13:50 UTC, dsvanlani commented on ui/public/icons/destinations/custom.svg
So I see that you have the font set to Nunito - but its not picking it up in the browser.  In general setting the font on text in SVG is pretty inconsistent across browser and definitely won't work for our customers running in `offline` environments.

The font for custom also seems pretty cramped.

Can we export these SVGs using `paths` instead of `text` tags?  We can see if it still looks cramped after using the correct font.

<img width="190" alt="image" src="https://github.com/observIQ/bindplane-op/assets/64915094/a237826a-a80e-4eda-a9fd-921b066014cf">

2023-06-28 17:10 UTC, kuiperda commented on ui/public/icons/sources/journald.svg
Ended up changing the journald icon to a generic notebook/journal after discussing with Josh.

2023-06-28 17:11 UTC, kuiperda commented on ui/public/icons/destinations/custom.svg
Did this and made the text a bit smaller for the custom icon

2023-06-28 17:11 UTC, dsvanlani approved these changes

2023-06-29 19:57 UTC, antonblock approved these changes

2023-06-29 20:34 UTC, merged