feat(UI): Delete and Duplicate current version from config page
observIQ/bindplane-op pull request #1239
Opened 2023-06-26 21:01 UTC by dsvanlani

### Proposed Change
This PR adds a hamburger menu to the `ConfigDetails` component which gives the users options to delete and to duplicate the current version when available.

<img width="1654" alt="image" src="https://github.com/observIQ/bindplane-op/assets/64915094/81fb8c8d-5187-4458-b33d-59825dc40ad0">

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-06-30 14:42 UTC, antonblock commented on ui/src/components/ConfigurationDetails/ConfigurationDetails.tsx
> +  Button,
```suggestion
```

2023-06-30 14:47 UTC, antonblock commented on ui/src/components/ConfigDetailsMenu/ConfigDetailsMenu.tsx
> +        open={duplicateDialogOpen}
```suggestion
        open={duplicateDialogOpen}
        onClose={() => setDuplicateDialogOpen(false)}
```
I wasn't able to close the modal without this

2023-06-30 14:56 UTC, antonblock commented on ui/src/components/ConfigDetailsMenu/ConfigDetailsMenu.tsx
> +      enqueueSnackbar(`Deleted config ${configName}`, { variant: "success" });
Nitpick but I think we should use `configuration` in the snackbar and confirmation modals, since we're using that in the navbar and duplication modal

2023-06-30 18:52 UTC, andykellr requested changes
Noticed when we were looking at it that the padding of the title bars is different. Make the top one `0 24px` and the `Topology` title bar similar.

Also got into a strange state where the duplicate dialog didn't disappear and the menu didn't change.

1) Create a duplicate
2) Delete the duplicate
3) Duplicate again

2023-07-05 14:53 UTC, andykellr approved these changes

2023-07-05 14:56 UTC, antonblock approved these changes

2023-07-06 16:20 UTC, merged