feat(ui): Overview page layout
observIQ/bindplane-op pull request #1253
Opened 2023-06-28 15:02 UTC by shazlehu

### Proposed Change

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-06-29 14:52 UTC, dsvanlani requested changes

2023-06-29 14:52 UTC, dsvanlani commented on ui/src/pages/overview/OverviewPage.tsx
> +          width: "25vw",
Can we set a min width on this stack to avoid horizontal scroll altogether?

2023-06-29 14:52 UTC, dsvanlani commented on ui/src/pages/overview/overview-page.module.scss
> +.root {
nit: Can we pick a better name for this class?

```suggestion
.destinations-paper {
```

2023-06-29 15:06 UTC, jmwilliams89 approved these changes

2023-07-05 15:37 UTC, dsvanlani approved these changes

2023-07-06 14:13 UTC, merged