feat(ui): Destinations table search
observIQ/bindplane-op pull request #1278
Opened 2023-07-06 22:21 UTC by shazlehu

### Proposed Change

https://app.vivifyscrum.com/boards/114813/sprint-backlog/376716/BPOP-1104

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-07-07 14:14 UTC, cpheps approved these changes

2023-07-10 16:05 UTC, dsvanlani requested changes
Its working well, but I have two requests:

1. Use `refetch` to update the data instead of a subscribe to more.
2. Debounce the refetch similar to the agents table search by 100ms.

2023-07-10 20:54 UTC, dsvanlani commented on ui/src/pages/destinations/DestinationsPage.tsx
> +    refetchWritePolicy: "merge",
What does this do? I can't find documentation on it

2023-07-10 21:00 UTC, dsvanlani approved these changes

2023-07-11 15:15 UTC, merged