feat(filelog): File Sorting and Reading of Only Current File
observIQ/bindplane-op pull request #1282
Opened 2023-07-09 16:50 UTC by Mrod1598

### Proposed Change

- Add New UI Page for FileLogFiltering 
- Update parameter handling to validate filelog 
- Update filelog processor

![image](https://github.com/observIQ/bindplane-op/assets/14144136/2e641b60-e349-4364-aadf-ac31a6381231)

note:
There is currently a bug with timestamp parsing so I've commented out that section until the fix gets in. 

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-07-10 12:03 UTC, cpheps commented on model/parameter.go
> +	if kind != reflect.Slice {
What is the expected value of kind? I'm curious if we can achieve this with a type switch rather than reflection.

2023-07-10 12:35 UTC, Mrod1598 commented on model/parameter.go
> +	if kind != reflect.Slice {
Yeah I was trying to be consistent with what we are doing for AWS but you're probably right that removing reflection where we can is better.

2023-07-12 18:43 UTC, dsvanlani commented
I was also able to save an invalid config by setting the sort type to alphabetical and I was not required to specify a Regex Key value:

<img width="870" alt="image" src="https://github.com/observIQ/bindplane-op/assets/64915094/02e16ee5-8be6-4af5-8e97-fb03dae31163">

2023-07-12 20:13 UTC, Mrod1598 commented on ui/src/components/ResourceConfigForm/ParameterInput/ParameterInput.tsx
> +          </>
Updated

2023-07-12 20:13 UTC, Mrod1598 commented on ui/src/components/ResourceConfigForm/ParameterInput/ParameterInput.tsx
> +  onValueChangeArg?: (v: any) => void;
Updated

2023-07-12 21:00 UTC, dsvanlani approved these changes

2023-07-13 12:25 UTC, cpheps commented on model/parameter.go
> +
Don't submit a change just for this unless you have others to group in.

2023-07-13 18:00 UTC, Mrod1598 commented on ui/src/components/ResourceConfigForm/ParameterInput/FileLogSortInput.tsx
> +          },
Updated

2023-07-14 01:13 UTC, cpheps approved these changes

2023-07-14 15:11 UTC, dsvanlani requested changes
After the recent changes I'm seeing console errors again.  We discussed a strategy to fix this by using the pattern in the AWS parameter input.

2023-07-14 19:19 UTC, dsvanlani approved these changes

2023-07-17 12:38 UTC, merged