feat(UI): Add additionalInfo to resource metadata + update Microsoft 365 source
observIQ/bindplane-op pull request #1321
Opened 2023-07-13 18:55 UTC by kuiperda

### Proposed Change
Adds an `additionalInfo` property to resource metadata. This corresponds to a [mui alert](https://mui.com/material-ui/react-alert/) being added in TitleSection.tsx. 

Intended for use on sources and utilized on the Microsoft 365 source which is our first use case where we want to clearly communicate certain configuration details to customers up front. 

The alert will show up right under the title description and the alert box will shrink to text size that takes less than one line. Documentation links will not wrap between lines. Could be expanded to allow other icon/color options. 

Example metadata in source.yaml that uses an additionalInfo property, which contains a required string `message` and an optional `documentation` array:
```
metadata:
  name: m365
  displayName: Microsoft 365
  icon: /icons/sources/microsoft_iis.svg
  description: Collect metrics and logs from Microsoft 365.
  additionalInfo:
    message: You must configure your tenant for logs, which can take 1 hour to be enabled and then up to 12 hours to become available. Metrics are reported once per day, but a report contains the metrics that were generated two days prior.
    documentation:
      - text: Read more
        url: https://docs.bindplane.observiq.com/docs/microsoft-365
```

What it looks like: 

![M365-source-configure](https://github.com/observIQ/bindplane-op/assets/44123852/84555a04-eba7-441e-a39c-eb25c80541f2)

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-07-14 15:29 UTC, dsvanlani requested changes

2023-07-14 15:29 UTC, dsvanlani commented on graphql/schema.graphqls
> +  documentation: [DocumentationLink]
I think the DocumentationLink is non nullable.

```suggestion
  documentation: [DocumentationLink!]
```

2023-07-14 15:29 UTC, dsvanlani commented on ui/src/components/DialogComponents/TitleSection.tsx
> +import { AdditionalInfoBlock } from "../../graphql/generated";
nit: Can you move this import to the top block?

2023-07-14 15:29 UTC, dsvanlani commented on ui/src/components/DialogComponents/TitleSection.tsx
> +            </span>
The `key` prop needs to be at the top level of the mapped component. Also a key that is possibly undefined is a bad choice, but I think making the documentationLink non nullable in the schema will fix that.

```suggestion
            <span key={d.url}>
              <a
                className={styles["doclink"]}
                href={d?.url}
                rel="noreferrer"
                target="_blank"
              >
                {d?.text}
              </a>{" "}
            </span>
```

2023-07-14 15:29 UTC, dsvanlani commented on ui/src/components/DialogComponents/TitleSection.tsx
> +          {additionalInfo.message}{" "}
Can we put this in typography and have the links on new lines?
```suggestion
          <Typography>{additionalInfo.message}</Typography>
```

2023-07-14 18:51 UTC, antonblock commented on resources/source-types/microsoft_365.yaml
> +      - text: Read more
```suggestion
      - text: Read More
```

2023-07-14 20:03 UTC, kuiperda reviewed
Responded to feedback but am still adding props so the `additionalInfo` gets passed to the 'Add Source' views, not just the 'Edit Source'. Will re-ping when this is completed. Thanks for the reviews!

2023-07-17 17:19 UTC, kuiperda reviewed
Passed props in more places so that the info alert shows up in AssistedConfig StepTwo add/edit source, and on the 'add source' in the topology of a configuration.

2023-07-17 17:23 UTC, kuiperda reviewed
With the new change to keep the title header visible while scrolling (on sources), the info alert can take up too much room. Maybe we could try collapsing it when scrolling? Here's what it looks like currently: 

<img width="912" alt="image" src="https://github.com/observIQ/bindplane-op/assets/44123852/595ae5e6-9899-49ec-b5a0-7835d5ca94a7">

2023-07-17 18:11 UTC, kuiperda reviewed
This is more of a question, if this seems right- 
- I'm noticing in the playground that sources without an additionalInfo property in their metadata do have an (empty) additionalInfo being returned. Dave mentioned that a 'Documentation' should be non-nullable but its value is actually null in these cases. 
- I'm also noticing that adding a completely empty additionalInfo to a source is allowed. Either way it  results in an empty alert being displayed if I kept {additionalInfo && (...)} as the conditional checker (instead of adding the `.message` check).

2023-07-17 18:13 UTC, kuiperda reviewed
Last thing- should I be adding tests for this component? And I'm curious if I should document the new metadata property somewhere.

2023-07-17 18:33 UTC, dsvanlani commented
> Last thing- should I be adding tests for this component? And I'm curious if I should document the new metadata property somewhere.

Tests are good, could test the TitleSection that it renders the alert.

2023-07-20 15:11 UTC, dsvanlani approved these changes

2023-07-20 15:38 UTC, antonblock approved these changes

2023-07-20 16:02 UTC, merged