feat: shell tab completion instructions
observIQ/bindplane-op pull request #138
Opened 2022-07-21 17:29 UTC by algchoo

### Proposed Change

added instructions for setting up tab completion for bash/zsh on linux/macos

##### Checklist
- [x] Changes are tested
- [ ] CI has passed

2022-07-21 17:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/observIQ/bindplane-op?pullRequest=138) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/observIQ/bindplane-op?pullRequest=138) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/observIQ/bindplane-op?pullRequest=138) it.</sub>

2022-07-21 20:21 UTC, jsirianni requested changes

2022-07-21 20:21 UTC, jsirianni commented on docs/install.md
> +`bindplanectl completion --zsh ><YOUR FPATH HERE>/_bindplanectl`
zsh is a sub command, not a flag
```suggestion
`bindplanectl completion zsh ><YOUR FPATH HERE>/_bindplanectl`
```

2022-07-26 15:37 UTC, dsvanlani commented
I was not able to get completion working with these instructions on Mac and zsh.

2022-07-28 13:28 UTC, jsirianni commented
I was able to get this working on Linux (zsh) but not macOS. I think it is working generally, but we have some consistency issues between macOS installs.

2022-07-29 19:47 UTC, jsirianni requested changes

2022-07-29 19:47 UTC, jsirianni commented on docs/install.md
> +3. `bindplane completion bash >/etc/bash_completion.d/bindplane` appends the output to a file in the bash completion directory
We should use `sudo tee` when redirecting output to a file owned by root, when not running as root.

2022-07-29 19:47 UTC, jsirianni commented on docs/install.md
> +3. `bindplane completion bash >/etc/bash_completion.d/bindplane` appends the output to a file in the bash completion directory
Lets always use bindplanectl when running commands, bindplane (binary) may not support cli in the future.

```suggestion
3. `bindplanectl completion bash >/etc/bash_completion.d/bindplanectl` appends the output to a file in the bash completion directory
```

2022-07-29 19:47 UTC, jsirianni commented on docs/install.md
> +#### macOS: bash
I am okay with removing this for now
1) I cant get it to work
2) Most macOS users will be using zsh

2022-07-29 20:14 UTC, algchoo commented on docs/install.md
> +#### macOS: bash
removed this portion of the instructions

2022-07-29 20:25 UTC, jsirianni approved these changes

2022-07-29 20:37 UTC, andykellr commented
It would be nice to add an .oh-my-zsh plugin, like https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/gh/gh.plugin.zsh

2022-07-29 20:42 UTC, andykellr commented
I'm good with merging this, but this is what I did:

1. Verify that compinit is already in .zshrc

2.
```sh
compinit; echo $fpath # /Users/andy/.oh-my-zsh/completions in the list but doesn't exist
mkdir /Users/andy/.oh-my-zsh/completions
bindplanectl completion zsh >/Users/andy/.oh-my-zsh/completions/_bindplanectl
```

3. Restart zsh

2022-07-29 20:53 UTC, dsvanlani approved these changes

2022-07-29 21:02 UTC, merged