feat: Update Rename Fields to match standards
observIQ/bindplane-op pull request #1430
Opened 2023-08-03 20:27 UTC by jmwilliams89

### Proposed Change
- Updates processor name to be plural
- Updates processor description to match name
- Updates field parameters to use `fields` instead of `keys`
- Add descriptions to field parameters

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-08-03 21:27 UTC, jsirianni approved these changes

2023-08-03 21:28 UTC, jsirianni requested changes
Looks good but we should bump the version. I **always** forget.

2023-08-04 15:23 UTC, antonblock approved these changes

2023-08-07 17:30 UTC, jsirianni approved these changes

2023-08-07 17:46 UTC, merged