feat: logzio destination
observIQ/bindplane-op pull request #148
Opened 2022-07-26 11:27 UTC by yotamloe

### Proposed Change
Addition of logz.io destination for logs metrics and traces
- Feature request issue: #78 
- ObservIQ-otel-collector pr for logzio support: https://github.com/observIQ/observiq-otel-collector/pull/554
##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-07-26 11:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/observIQ/bindplane-op?pullRequest=148) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/observIQ/bindplane-op?pullRequest=148) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/observIQ/bindplane-op?pullRequest=148) it.</sub>

2022-07-26 12:57 UTC, jsirianni commented
Hi @yotamloe, thank you for this contribution. Before I run CI, can you resolve the following issues?

```
--- FAIL: TestValidateDestinationTypes (0.00s)
    --- FAIL: TestValidateDestinationTypes/destination-types/logzio.yaml (0.00s)
        resources_test.go:82: 
            	Error Trace:	/home/jsirianni/git/bindplane-op.logzio/resources/resources_test.go:82
            	Error:      	Received unexpected error:
            	            	3 errors occurred:
            	            		* template: logs.exporters:1:6: executing "logs.exporters" at <eq .enable_logs>: error calling eq: missing argument for comparison
            	            		* template: metrics.exporters:1:6: executing "metrics.exporters" at <eq .enable_metrics>: error calling eq: missing argument for comparison
            	            		* template: traces.exporters:1:6: executing "traces.exporters" at <eq .enable_tracing>: error calling eq: missing argument for comparison
            	            	
            	Test:       	TestValidateDestinationTypes/destination-types/logzio.yaml
FAIL
FAIL	github.com/observiq/bindplane-op/resources	0.021s
FAIL
```

For boolean conditions, you can omit the `eq`
```
{{ if .enable_metrics }}
```

These tests can be run with `go test ./resources` or `make test`.

2022-07-26 13:03 UTC, yotamloe commented
Hey @jsirianni thanks for the quick reply, I'll fix this issue

2022-07-26 17:39 UTC, jsirianni requested changes
Giving this a spin now. Some initial thoughts:

Can you re-order the parameters so that each token comes after the enable toggle that matches it? I think this will look nicer in the UI.

![Screenshot from 2022-07-26 13-35-30](https://user-images.githubusercontent.com/23043836/181073517-d6e6b18e-b60e-4ba6-8fb3-02325253efd0.png)

2022-07-26 17:39 UTC, jsirianni commented on resources/destination-types/logzio.yaml
> +      label: Logs_token
Label names can have spaces
```suggestion
      label: Logs Token
```

2022-07-28 15:25 UTC, jsirianni approved these changes
Thanks!

2022-07-28 19:10 UTC, andykellr approved these changes

2022-07-28 19:11 UTC, merged