feat: Users can duplicate a config via REST and UI
observIQ/bindplane-op pull request #159
Opened 2022-07-27 13:36 UTC by dsvanlani

### Proposed Change
It can be useful to make a copy of an existing config if you wanted to adjust sources slightly.  

This PR:
- Adds a REST endpoint `PUT /v1/configurations/:name/duplicate` will copy the `Spec` of a config into a new one, changing only the `metadata.name`, `metadata.id`, and `spec.selector.matchLabels` fields.
- Add a "Duplicate" Button on the configuration view page:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/64915094/181260269-9f44e15a-8497-4466-aba7-3842d9fdc005.png">
<img width="841" alt="image" src="https://user-images.githubusercontent.com/64915094/181260384-f4eb4bb2-5ba1-4054-bab6-4eb289ea3c45.png">

##### Checklist
- [x] Changes are tested
- [ ] CI has passed

2022-07-27 15:39 UTC, andykellr commented on internal/rest/api.go
> +	router.PUT("/configurations/:name/duplicate", func(c *gin.Context) { duplicateConfig(c, bindplane) })
I think semantically a `POST` is more appropriate here. A `PUT` would normally imply that a new resource is being created at this path. Instead this endpoint performs an action and subsequent calls to it can produce different resources.

Another alternative would be to add `PUT("/configurations/:name", ...)` with a way to specify a source configuration (url or body param), but this would suggest that we create other configs this way (e.g. raw and parameterized) and I think we want to just keep using `/apply` for that.

2022-07-27 15:44 UTC, andykellr commented on model/configuration.go
> +	new.Metadata.ID = name
```suggestion
	new.Metadata.ID = uuid.NewString()
```

2022-07-27 15:47 UTC, andykellr commented on model/configuration.go
> +	*new = *c
Even though it is legal go, shadowing the builtin `new` function is confusing here. Call it `copy` instead.

Also, this is sufficient:

```go
copy := *c
```

And then change the return to

```go
return &copy
```

2022-07-27 15:47 UTC, dsvanlani commented on internal/rest/api.go
> +	router.PUT("/configurations/:name/duplicate", func(c *gin.Context) { duplicateConfig(c, bindplane) })
Ok - sounds like this should just be a POST.

2022-07-27 16:01 UTC, andykellr requested changes
Looks good other than those few comments.

2022-07-29 14:27 UTC, andykellr approved these changes

2022-07-29 14:30 UTC, merged