feat(destination-type): Splunk Observability Cloud (SignalFX)
observIQ/bindplane-op pull request #168
Opened 2022-07-28 01:11 UTC by jsirianni

### Proposed Change

***NOTE***: observiq-otel-collector does not support the exporters required by this destination type. This PR should not be merged before support is added to the collector. I will have a PR adding the exporters tomorrow.

Splunk Observability Cloud (SignalFX) requires the following exporters
- SAPM: traces
- Splunk HEC: logs
- SignalFX: metrics

The token for all three telemetry types appears to be the same, however, the platform can enable / disable features (logs will not work by default). Because of this, the destination type has toggles for each telemetry type.

The resource detection processor is **required** per the signalfx exporter docs.

I was able to get trace and metrics working without issue, however, logs gave 403 errors. This is because I do not have logging enabled, and the Splunk UI indicates that I need a Splunk Enterprise account when I try to setup logging. I am confident that the configuration is correct as it is derived from the configuration given to me during a splunk collector install.

```yaml
# splunk log exporter config generated by Splunk's platform
...
  splunk_hec:
    token: "<my token>"
    endpoint: "https://ingest.us1.signalfx.com/v1/log"
    source: "otel"
    sourcetype: "otel"
...
```

![Screenshot from 2022-07-27 20-46-07](https://user-images.githubusercontent.com/23043836/181398896-3bf0d3d5-70a7-4198-9c30-f716296f67ba.png)

Metrics

![Screenshot from 2022-07-27 20-27-38](https://user-images.githubusercontent.com/23043836/181397764-526b0f24-1508-4ac8-8662-1b8f263a8d13.png)

Traces

![Screenshot from 2022-07-27 20-09-55](https://user-images.githubusercontent.com/23043836/181397775-6d75b012-3336-4bcc-be32-5b0c1569392e.png)

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-07-28 13:55 UTC, jsirianni commented
The collector will need to merge this https://github.com/observIQ/observiq-otel-collector/pull/593. We will also want to wait for a release.

2022-08-09 14:33 UTC, andykellr approved these changes

2022-08-09 16:03 UTC, dsvanlani requested changes

2022-08-09 16:03 UTC, dsvanlani commented on resources/destination-types/signalfx.yaml
> +apiVersion: bindplane.observiq.com/v1beta
```suggestion
apiVersion: bindplane.observiq.com/v1
```

2022-08-09 17:22 UTC, merged