feat(source-type): Add log support to Zookeeper source type
observIQ/bindplane-op pull request #197
Opened 2022-08-01 16:34 UTC by jsirianni

### Proposed Change

Added log support to Zookeeper source type.

![Screenshot from 2022-08-01 12-34-24](https://user-images.githubusercontent.com/23043836/182198999-1279cd6a-fdd1-41ff-8092-e96b21413f0b.png)

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-08-03 16:32 UTC, dsvanlani approved these changes
LGTM.

Was able to make this OTel configuration with the zookeeper source

```yaml
receivers:
    plugin/zookeeper__source0:
        parameters:
            file_path:
                - /opt/zookeeper/logs/zookeeper.log
            start_at: end
        path: $OIQ_OTEL_COLLECTOR_HOME/plugins/zookeeper_logs.yaml
    zookeeper/zookeeper__source0:
        collection_interval: 60s
        endpoint: localhost:2181
processors:
    batch/otlp_grpc__otlp: null
    resourcedetection/zookeeper__source0:
        detectors:
            - system
        system:
            hostname_sources:
                - os
exporters:
    logging/logging__logging-dest:
        logLevel: debug
    otlp/otlp_grpc__otlp:
        endpoint: 0.0.0.0:4317
        tls:
            insecure: true
service:
    pipelines:
        logs/zookeeper__source0__logging-dest:
            receivers:
                - plugin/zookeeper__source0
            processors:
                - resourcedetection/zookeeper__source0
            exporters:
                - logging/logging__logging-dest
        logs/zookeeper__source0__otlp:
            receivers:
                - plugin/zookeeper__source0
            processors:
                - resourcedetection/zookeeper__source0
                - batch/otlp_grpc__otlp
            exporters:
                - otlp/otlp_grpc__otlp
        metrics/zookeeper__source0__logging-dest:
            receivers:
                - zookeeper/zookeeper__source0
            processors:
                - resourcedetection/zookeeper__source0
            exporters:
                - logging/logging__logging-dest
        metrics/zookeeper__source0__otlp:
            receivers:
                - zookeeper/zookeeper__source0
            processors:
                - resourcedetection/zookeeper__source0
                - batch/otlp_grpc__otlp
            exporters:
                - otlp/otlp_grpc__otlp

```

2022-08-04 14:43 UTC, ryancgoins commented
Update description to: "Collect metrics and logs from ZooKeeper"

2022-08-04 14:57 UTC, ryancgoins requested changes
Update description to: "Collect metrics and logs from Cassandra"

2022-08-04 17:23 UTC, ryancgoins approved these changes

2022-08-04 19:05 UTC, merged