feat(source-type): SAP Hana logs source type
observIQ/bindplane-op pull request #200
Opened 2022-08-01 18:44 UTC by jsirianni

### Proposed Change

Added SAP Hana source type with logs only. Metrics is commented out, as we need to wait for a collector release that includes the Hana receiver.

![Screenshot from 2022-08-01 14-44-06](https://user-images.githubusercontent.com/23043836/182221188-fe180d82-0043-4b2a-aef8-8d41b9e36986.png)

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-08-03 16:46 UTC, dsvanlani requested changes
Nit: I think if metrics support is not in we should not have the relevant_if for logs.

![image](https://user-images.githubusercontent.com/64915094/182663850-9f96c7c7-9c24-4cd9-ac6e-ccbabefe0268.png)

![image](https://user-images.githubusercontent.com/64915094/182663884-34dbd278-2f98-44e0-adf3-ba5ec82cdf44.png)


Config rendering looks good.

```yaml
receivers:
    plugin/hana__source0:
        parameters:
            file_path:
                - /usr/sap/*/HDB*/*/trace/*.trc
            start_at: end
            timezone: UTC
        path: $OIQ_OTEL_COLLECTOR_HOME/plugins/sap_hana_logs.yaml
processors:
    batch/otlp_grpc__otlp: null
    resourcedetection/hana__source0:
        detectors:
            - system
        system:
            hostname_sources:
                - os
exporters:
    otlp/otlp_grpc__otlp:
        endpoint: 0.0.0.0:4317
        tls:
            insecure: true
service:
    pipelines:
        logs/hana__source0__otlp:
            receivers:
                - plugin/hana__source0
            processors:
                - resourcedetection/hana__source0
                - batch/otlp_grpc__otlp
            exporters:
                - otlp/otlp_grpc__otlp
```

2022-08-03 18:17 UTC, jsirianni commented
@dsvanlani totally agree, done.

2022-08-04 14:34 UTC, ryancgoins commented on resources/source-types/sap_hana.yaml
> +  description: SAP Hana logs
```suggestion
  description: Collect logs from SAP Hana 
```

I'm working on a updating our Stanza style guide for us to use with BindPlane OP so we have a standard here. For now, let's use the above format for descriptions

2022-08-04 17:23 UTC, ryancgoins approved these changes

2022-08-04 19:04 UTC, merged