feat(source-type): Oracle Database (logs)
observIQ/bindplane-op pull request #201
Opened 2022-08-01 19:03 UTC by jsirianni

### Proposed Change

Added source type for Oracle Database logs.

![Screenshot from 2022-08-01 15-03-03](https://user-images.githubusercontent.com/23043836/182225090-3642d8da-4e7e-4b6f-8d84-edfb0214a953.png)

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-08-02 20:53 UTC, andykellr commented on resources/source-types/oracledb.yaml
> +  description: Oracle Database log parser
```suggestion
  description: Log parsing for alert, audit, and listener logs.
```

2022-08-03 17:08 UTC, dsvanlani requested changes
See @andykellr comment.

2022-08-03 18:12 UTC, jsirianni commented
Latest copy

![Screenshot from 2022-08-03 14-10-57](https://user-images.githubusercontent.com/23043836/182679254-5818908e-795c-46cd-8e51-c52d0f338bf1.png)

2022-08-03 21:05 UTC, ryancgoins approved these changes

2022-08-04 02:06 UTC, merged