feat(processor): Add / Delete Attributes / Resources
observIQ/bindplane-op pull request #205
Opened 2022-08-03 14:16 UTC by dsvanlani

### Proposed Change
Cleaned up version of #177 
- Adds 4 new processors: add_attribute, add_resource, delete_attribute, delete_resource

With this processor section:

![image](https://user-images.githubusercontent.com/64915094/182630832-9cc18b66-c0fe-4736-afda-709846d1ce56.png)

I was able to produce this config:

```yaml
receivers:
    plugin/file__source0:
        parameters:
            encoding: utf-8
            file_path:
                - /tmp/file.log
            log_type: file
            multiline_line_start_pattern: ""
            parse_format: none
            start_at: end
        path: $OIQ_OTEL_COLLECTOR_HOME/plugins/file_logs.yaml
processors:
    attributes/add_attribute__file__source0__processor1:
        actions:
            - action: upsert
              key: computer
              value: daves-macbook-pro
            - action: upsert
              key: something
              value: blah
    attributes/delete_attribute__file__source0__processor2:
        actions:
            - action: delete
              key: one
            - action: delete
              key: two
            - action: delete
              key: three
    resource/add_resource__file__source0__processor3:
        attributes:
            - action: upsert
              key: blah
              value: baz
            - action: upsert
              key: foo
              value: bar
    resource/delete_resource__file__source0__processor0:
        attributes:
            - action: delete
              key: blah
            - action: delete
              key: foo
            - action: delete
              key: bar
    resourcedetection/file__source0:
        detectors:
            - system
        system:
            hostname_sources:
                - os
exporters:
    logging/logging__info:
        logLevel: info
service:
    pipelines:
        logs/file__source0__info:
            receivers:
                - plugin/file__source0
            processors:
                - resourcedetection/file__source0
                - resource/delete_resource__file__source0__processor0
                - attributes/add_attribute__file__source0__processor1
                - attributes/delete_attribute__file__source0__processor2
                - resource/add_resource__file__source0__processor3
            exporters:
                - logging/logging__info
```

With these processor configurations:

**Add Attribute**
![image](https://user-images.githubusercontent.com/64915094/182631189-a72492d9-58d4-4d9b-bcaf-346685ef0af7.png)

**Add Resource**
![image](https://user-images.githubusercontent.com/64915094/182631334-f5ebad3f-e633-48ec-91c2-c94489d92adb.png)

**Delete Attribute**
![image](https://user-images.githubusercontent.com/64915094/182631417-a9440ce1-d9fe-4e09-a349-3e1deec220d5.png)

**Delete Resource 
![image](https://user-images.githubusercontent.com/64915094/182631572-2e3038e4-7abf-4509-854b-e931f18437a8.png)

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-08-03 19:51 UTC, jsirianni requested changes

2022-08-03 19:51 UTC, jsirianni commented on resources/processor-types/add_attribute.yaml
> +      label: Map Type Param
```suggestion
      label: Attributes
```

2022-08-03 19:51 UTC, jsirianni commented on resources/processor-types/add_resource.yaml
> +      label: Map Type Param
```suggestion
      label: Resources
```

2022-08-03 20:30 UTC, jsirianni approved these changes

2022-08-03 20:50 UTC, ryancgoins commented on resources/processor-types/add_attribute.yaml
> +    - name: action
I think we should move the action above the parameter. Seems more natural to select that first and then enter the key/value pairs

2022-08-03 20:51 UTC, ryancgoins commented on resources/processor-types/add_attribute.yaml
> +    - name: enable_metrics
Can we add a description to this section that says "Select which types of telemetry you'd like to enable this processor for."

2022-08-03 20:54 UTC, ryancgoins reviewed
Added some minor thoughts on copy / layout. Otherwise looks good

2022-08-04 00:08 UTC, dsvanlani commented on resources/processor-types/add_attribute.yaml
> +    - name: enable_metrics
This could be a `multi-enum` parameter type.

2022-08-04 01:57 UTC, jsirianni commented on resources/processor-types/add_attribute.yaml
> +    - name: action
I pushed a change to move action to the top.

![Screenshot from 2022-08-03 21-57-02](https://user-images.githubusercontent.com/23043836/182746502-bf08775c-e16a-4cf5-bc18-ff230ae4fad6.png)

2022-08-04 02:05 UTC, jsirianni commented on resources/processor-types/add_attribute.yaml
> +    - name: enable_metrics
Bool values do not display their descriptions currently. 

We could do a multi select enum, which would have a single description with all three pipelines as options in the select. It would make the template somewhat more complicated. We would need to loop over the values, checking to see if the value is <pipeline type> and then use it.

2022-08-04 17:00 UTC, dsvanlani commented
@ryancgoins This is the new layout for the Telemetry section for these processors:

![image](https://user-images.githubusercontent.com/64915094/182908389-49600b6b-8211-4aa2-8f52-f8914390623c.png)

2022-08-04 17:20 UTC, ryancgoins commented
LGTM

2022-08-04 19:05 UTC, merged