fix: Remove feature gated metrics from existing metric toggles.
observIQ/bindplane-op pull request #295
Opened 2022-08-18 19:54 UTC by dsvanlani

### Proposed Change
This PR removes metrics that rely on the feature gate `emitMetricsWithDirectionAttribute` to be enabled.

A discussion on this can be found in the VCenter receiver readme in the otel collector contribe [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/vcenterreceiver).

**This is a breaking change for anyone using this feature**

Right now we validate that a source configuration values for `parameters` are one of `validValues`.  We are removing valid values from this list so if someone had say `system.network.packets.receive` disabled with the metric toggles then their source would no longer be valid.

To fix this the customer would need to delete the source and reconfigure it.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-08-20 02:19 UTC, andykellr commented on resources/source-types/elasticsearch.yaml
> -        - elasticsearch.node.disk.io.write
The cluster.io metrics are feature gated, but oddly it doesn't seem that the disk.io metrics are affected.

2022-08-20 02:19 UTC, andykellr requested changes
elasticsearch disk metrics should probably remain.

2022-08-22 18:02 UTC, andykellr approved these changes

2022-08-23 13:05 UTC, jsirianni approved these changes

2022-08-23 13:06 UTC, merged