Feat/resource form design 2
observIQ/bindplane-op pull request #341
Opened 2022-09-06 19:24 UTC by dsvanlani

### Proposed Change

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-09-07 15:43 UTC, Mrod1598 approved these changes

2022-09-07 15:43 UTC, Mrod1598 commented on resources/source-types/iis.yaml
>        label: Metric Filtering
All the other sources say just `Filtering` here.

2022-09-07 15:43 UTC, Mrod1598 commented on resources/source-types/hbase.yaml
>        description: Enable to scrape master server's JMX port.
Would it be a meaningful change to add a disclaimer to the ones that don't have metric filtering? not sure if we expect users to click through and checkout multiple sources but if going from one with filtering and one without filtering it might be confusing why some don't support filtering and some do.

2022-09-07 15:43 UTC, Mrod1598 commented on resources/source-types/aerospike.yaml
>          - name: enable_metrics
do we do any validation on hostname/port or do we want to?
![image](https://user-images.githubusercontent.com/14144136/188918348-c3016e7f-8dab-4075-9954-53b2b49652ce.png)

2022-09-07 15:45 UTC, Mrod1598 requested changes
Looks good over all with a few comments ^(misclicked)

2022-09-08 02:21 UTC, andykellr commented
I noticed a strange issue testing the macOS source. There is a `Start At` field that is probably supposed to be part of the System Logs section. If I toggle `Enable Logs` on and off, another field is added.

https://user-images.githubusercontent.com/2660251/189019086-6b98e517-41f7-4b70-9d9b-d0f82d2ec95d.mov

2022-09-08 14:36 UTC, andykellr commented on model/parameter.go
> +	SectionHeader *bool `json:"sectionHeader,omitempty" yaml:"gridColumns,omitempty"`
```suggestion
	SectionHeader *bool `json:"sectionHeader,omitempty" yaml:"sectionHeader,omitempty"`
```

2022-09-08 15:26 UTC, andykellr commented on model/parameter.go
> +			}
Even if you add to errs here, it always returns nil.

I would recommend refactoring validateOptions and validateMetricCategories to take `errs validation.Errors` (which is built on multierror) and add them directly there.

We could consider refactoring the other methods of validateDefinition similarly but I left them alone because they all only report a single error (or nil).

2022-09-08 17:57 UTC, andykellr commented on model/parameter_test.go
> +			require.Error(t, err)
I think we should validate the text of the error.

Also, it would be good to include in `validation_test.go` a few examples of these test cases with actual yaml files (in the testfiles/validate folder)

2022-09-09 03:08 UTC, andykellr commented on resources/source-types/aerospike.yaml
>          - name: enable_metrics
The following issues mention this. I think considering that this behavior hasn't changed with this PR, it's ok to leave as is. We should consider allocating these issues if we think this is important.

observiq/iris#915 
observiq/iris#1168
observiq/iris#1169

2022-09-09 03:13 UTC, andykellr commented on ui/src/components/ResourceConfigForm/ParameterInput/MetricsParamInput.tsx
> +                    Select All
In bindplane-og we used `Enable All | Enable KPIs Only | Disable All`

We have a little less room here, but I wonder if we should use `None | KPIs | All`

2022-09-09 03:22 UTC, andykellr requested changes
I think this generally looks really great besides a few pieces of feedback.

The video I posted is a real issue. The same thing happens with cassandra.

I'd like to load every source page before approving this, but I think I'll wait until the few known issues are addressed.

2022-09-12 13:34 UTC, dsvanlani commented on resources/source-types/host.yaml
>        validValues:
Good catch.

2022-09-12 13:35 UTC, dsvanlani commented on resources/source-types/hbase.yaml
>        description: Enable to scrape master server's JMX port.
I'm gonna defer this one to @ryancgoins

2022-09-12 14:53 UTC, dsvanlani commented on ui/src/components/ResourceConfigForm/ParameterInput/MetricsParamInput.tsx
> +                    Select All
I think that would work.  RIght now we dont support a `KPIs` button, in the future we would do this by adding a `kpi: true` field to the parameters like this:

```yaml
options:
  metricCategories:
    - label: Postgres Metrics
       metrics:
         - name: kpi.metric
           kpi: true
```

I can change the copy to Enable All / Disable All though, which I think is more clear.

2022-09-12 14:55 UTC, ryancgoins commented on resources/source-types/hbase.yaml
>        description: Enable to scrape master server's JMX port.
Great call out @Mrod1598. I don't think we need this in the UI, but definitely in the documentation. I've created a ticket for the docs to be updated

2022-09-12 15:58 UTC, Mrod1598 requested changes
found a couple more duplication bugs.

2022-09-12 15:58 UTC, Mrod1598 commented on resources/source-types/hbase.yaml
>        description: Enable to scrape master server's JMX port.
seems the hbase metric toggle has the same issue that the other one did.
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/14144136/189693356-a5995db7-777e-4ae1-be3c-c9f1d8b9cb6f.png">. its the master metrics toggle and the region metrics toggle.

2022-09-12 15:58 UTC, Mrod1598 commented on resources/source-types/mysql.yaml
>        type: bool
mysql doing the multi `start_at` too 
<img width="928" alt="image" src="https://user-images.githubusercontent.com/14144136/189696148-a4c582b6-6043-4964-b8d5-064b835b1d96.png">

2022-09-12 15:58 UTC, Mrod1598 commented on resources/source-types/host.yaml
>        label: Load Metrics
host has some weird formatting
<img width="923" alt="image" src="https://user-images.githubusercontent.com/14144136/189696991-886e4391-1f53-4c16-876a-befbc97f2f55.png">

2022-09-12 15:58 UTC, Mrod1598 commented on resources/source-types/tomcat.yaml
>        type: bool
tomcat has the same issue as others with the logs toggle.
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/14144136/189697813-80227462-176d-4bcf-91a8-f112d50ad046.png">

Also, these two fields still show up when toggle is off.
<img width="903" alt="image" src="https://user-images.githubusercontent.com/14144136/189698142-cad46f01-39aa-42bd-802b-b3bad60ef933.png">

2022-09-12 15:58 UTC, Mrod1598 commented on resources/source-types/mysql.yaml
>        type: bool
start_at is in two spots that don't seem to make sense. (seems seperate from the duplication bug.)
<img width="895" alt="image" src="https://user-images.githubusercontent.com/14144136/189700185-c6d0505a-2240-4a38-bb85-0964d3105108.png">

2022-09-12 17:20 UTC, dsvanlani commented on resources/source-types/mysql.yaml
>        type: bool
@Mrod1598 I went ahead and added in verification that we are not duplicating parameter names - which fixes all these issues.  

```go
func (s *ResourceTypeSpec) validateNoDuplicateParameterNames(errs validation.Errors) {
	// visited is a map of parameter names to bool
	visited := make(map[string]bool, 0)

	for _, p := range s.Parameters {
		if visited[p.Name] {
			errs.Add(
				errors.New(
					fmt.Sprintf("found multiple parameters with name %s", p.Name),
				),
			)
		} else {
			visited[p.Name] = true
		}
	}
}
```

2022-09-12 17:28 UTC, dsvanlani commented on resources/source-types/host.yaml
>        label: Load Metrics
Yeah, i agree I'm not sure what to do about this as it was not included in the design.  I discussed with @ryancgoins and we removed the copy for each metric parameter so it looks a bit better.

![image](https://user-images.githubusercontent.com/64915094/189718251-f3c8cc9a-b1e4-45c7-b428-5327e98f05bd.png)

2022-09-12 18:59 UTC, ryancgoins commented on resources/source-types/host.yaml
>        label: Load Metrics
Is there a reason we don't format it using the same "Filtering" setting and then everything exposed under that in 2 columns?

2022-09-12 19:28 UTC, dsvanlani commented on resources/source-types/host.yaml
>        label: Load Metrics
Well - for backwards compatibility reasons each of the metrics is a separate parameter.  I can investigate how we could use them as one large metrics parameter.

2022-09-12 19:58 UTC, Mrod1598 approved these changes
LGTM

2022-09-12 20:11 UTC, merged