feat(cli): Allows bindplanectl get commands to take multiple arguments.
observIQ/bindplane-op pull request #358
Opened 2022-09-12 20:19 UTC by shazlehu

Also refactored all the 'get' commands to use the generic getImpl function. 
Resolves observiq/iris#123

### Proposed Change

'get' commands can now take multiple arguments, e.g.:

```
╰➤  bindplanectl get agents 0738a9b0-7c36-46ae-800e-98b61f763654 caf962be-3950-4c13-a60b-10324f0bd304
ID                                  	NAME             	VERSION	STATUS      	CONNECTED 	DISCONNECTED	LABELS
0738a9b0-7c36-46ae-800e-98b61f763654	Sams-M1-Pro.local	v1.7.0 	Connected   	121h42m19s	-           	configuration=Localhost
caf962be-3950-4c13-a60b-10324f0bd304	Sams-M1-Pro.local	v1.7.0 	Disconnected	-         	121h43m54s  	configuration=Localhost
```

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-09-12 20:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/observIQ/bindplane-op?pullRequest=358) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/observIQ/bindplane-op?pullRequest=358) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/observIQ/bindplane-op?pullRequest=358) it.</sub>

2022-09-12 21:11 UTC, dsvanlani requested changes
Small nits and a suggestion for implementation.  Working great, and my suggestion for not returning on first error need not hold this PR up.

2022-09-12 21:11 UTC, dsvanlani commented on internal/cli/commands/get/get.go
> +					return fmt.Errorf("no %s found with name %s", resourceName, name)
This is working great, but maybe we don't have to return here, say I request a source-type that exists and one that does not:

```bindplanectl get source-types host macOStypo```

I think we should print out all the items that we find and then all the errors that we accrue.  Right now that returns

```
Error: unable to get /source-types/macOSTYPo, got 404 Not Found
exit status 1
```

But it would be nice if it was something like 
```sh
NAME    DISPLAY 
host    Host   

source-type not found: macOSTypo
```

Again, its working great as is but I'd be curious @jsirianni and @andykellr take.

2022-09-12 21:11 UTC, dsvanlani commented on internal/cli/commands/get/get.go
> +// 'all' is a funtion that implements a call for all of the command type, e.g.
```suggestion
// 'all' is a function that implements a call for all of the command type, e.g.
```

2022-09-13 15:44 UTC, antonblock commented on internal/cli/commands/get/source_types.go
>  		RunE: getImpl(bindplane, "source-type", getter[*model.SourceType]{
```suggestion
		RunE: getImpl(bindplane, "source-types", getter[*model.SourceType]{
```
This was already here, but we should be consistent with pluralized `resourceName`

2022-09-13 15:44 UTC, antonblock commented on internal/cli/commands/get/agent_versions.go
> +//	http://www.apache.org/licenses/LICENSE-2.0
```suggestion
//      http://www.apache.org/licenses/LICENSE-2.0
```
I think this might be a tab on accident? It shows up as 2 chars for me in VS code

2023-01-21 00:09 UTC, shazlehu commented on internal/cli/commands/get/get.go
> +					return fmt.Errorf("no %s found with name %s", resourceName, name)
Added this feature

```
╰➤  b get source-types host macOStypo
NAME    DISPLAY 
host    Host   
Error: 2 errors occurred:
        * unable to get /source-types/macOStypo, got 404 Not Found
        * no source-type found with name macOStypo


exit status 1
```

2023-02-10 20:10 UTC, andykellr approved these changes

2023-02-10 21:08 UTC, andykellr approved these changes

2023-02-13 18:32 UTC, antonblock approved these changes

2023-02-17 16:45 UTC, merged