fix(UI) Styled the measurement control bar on the topology graphs per design.
observIQ/bindplane-op pull request #458
Opened 2022-10-11 22:07 UTC by shazlehu

### Proposed Change

This fixes the styling on the menu selecting Logs, Metrics, or Traces in the overview & configuration graphs. Also cleans up some of the naming of the .scss files.

##### Checklist

- [ ] Changes are tested
- [ ] CI has passed

2022-10-12 13:50 UTC, dsvanlani requested changes
Looks great, just some small things.

2022-10-12 13:50 UTC, dsvanlani commented on ui/src/components/MeasurementControlBar/MeasurementControlBar.tsx
> +import styles from "./measurement.bar.styles.module.scss";
nit: I've been using snake-case for .scss files.  Can we rename this file to`measurement-control-bar.module.scss` ?

2022-10-12 13:50 UTC, dsvanlani commented on ui/src/components/MeasurementControlBar/MeasurementControlBar.tsx
> +      <Toolbar classes={{ root: styles.toolbar }}>
```suggestion
      <Toolbar classes={{ root: styles.toolbar }} key={t}>
```

2022-10-12 13:50 UTC, dsvanlani commented on ui/src/components/MeasurementControlBar/MeasurementControlBar.tsx
> +      <Toolbar classes={{ root: styles.toolbar }}>
<img width="733" alt="image" src="https://user-images.githubusercontent.com/64915094/195359266-6283628d-c139-4484-bbdd-1c5ae633ab13.png">

2022-10-12 13:50 UTC, dsvanlani commented on ui/src/components/MeasurementControlBar/MeasurementControlBar.tsx
> +          <Stack>
```suggestion
          <Stack key={p}>
```

2022-10-12 13:50 UTC, dsvanlani commented on ui/src/components/MeasurementControlBar/measurement.bar.styles.module.scss
> +  border: 2px solid;
```suggestion
  border: 2px solid colors.$transparent;
```

2022-10-12 13:50 UTC, dsvanlani commented on ui/src/components/MeasurementControlBar/measurement.bar.styles.module.scss
> +  border-color: colors.$transparent;
```suggestion
```

2022-10-12 13:50 UTC, dsvanlani commented on ui/src/components/MeasurementControlBar/measurement.bar.styles.module.scss
> +  //  border-bottom: 1px solid colors.$mui-transparent-gray;
```suggestion
```

2022-10-12 13:50 UTC, dsvanlani commented on ui/src/styles/_colors.scss
> +// taken from the design
```suggestion
```

2022-10-12 15:27 UTC, shazlehu commented on ui/src/components/MeasurementControlBar/MeasurementControlBar.tsx
> +      <Toolbar classes={{ root: styles.toolbar }}>
This variable isn't available to the tool bar.

2022-10-12 15:33 UTC, shazlehu commented on ui/src/components/MeasurementControlBar/MeasurementControlBar.tsx
> +      <Toolbar classes={{ root: styles.toolbar }}>
I'm also not seeing this error. I've found it's typically caused when you map an array to DOM elements, which we aren't doing in this case.

2022-10-12 17:17 UTC, dsvanlani commented on ui/src/components/MeasurementControlBar/MeasurementControlBar.tsx
> +      <Toolbar classes={{ root: styles.toolbar }}>
Ooops, I meant you have to put it on the `<Stack>` - which we're mapping the TELEMETRY_TYPES to

2022-10-12 17:44 UTC, dsvanlani approved these changes
Just the one key prop issue, but looks good to me 👍 .

2022-10-12 17:48 UTC, shazlehu commented on ui/src/components/MeasurementControlBar/MeasurementControlBar.tsx
> +      <Toolbar classes={{ root: styles.toolbar }}>
Git it, fixed.

2022-10-14 19:46 UTC, andykellr approved these changes

2022-10-14 19:47 UTC, merged