feat: Custom sources and destinations
observIQ/bindplane-op pull request #469
Opened 2022-10-13 19:28 UTC by shazlehu

### Proposed Change
Adds custom sources & destinations, where the user can insert their own yaml into a config.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-10-13 19:38 UTC, andykellr approved these changes

2022-10-13 21:00 UTC, jsirianni requested changes

2022-10-13 21:00 UTC, jsirianni commented on resources/source-types/custom.yaml
> +  icon: /icons/destinations/custom.svg
This works but it is not using the source custom.svg.

2022-10-13 21:00 UTC, jsirianni commented on resources/source-types/custom.yaml
> +  icon: /icons/destinations/custom.svg
We could share a single svg for both, or fix this path.

2022-10-14 14:01 UTC, jsirianni approved these changes

2022-10-14 18:43 UTC, merged