feat: MongoDB Atlas source
observIQ/bindplane-op pull request #509
Opened 2022-10-27 18:54 UTC by cpheps

### Proposed Change
Created a MongoDB Atlas source.

Some limitations:
- The receiver allows multiple `project` structures to be specified for alerts and logs. Sources doesn't currently support an array of structs so I made it so you can only configure a single project. You would need multiple instances of this source for multiple projects.
- The alert collection in `poll` mode ideally needs a storage extension. There's currently no way to reference a storage extension in the `receiver` block.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-10-27 19:55 UTC, jsirianni requested changes

2022-10-27 19:55 UTC, jsirianni commented on resources/source-types/mongodb_atlas.yaml
> +    - name: granularity
I think it would be nice to link to documentation here.

Example from Elasticsearch
```yaml
    - name: nodes
      label: Collection Scope
      documentation:
        - text: Read more
          url: https://www.elastic.co/guide/en/elasticsearch/reference/7.9/cluster.html#cluster-nodes.
```

2022-10-27 19:55 UTC, jsirianni commented on resources/source-types/mongodb_atlas.yaml
> +    - name: granularity
Also, this option does not seem to be used in the receiver config.

2022-10-27 19:58 UTC, jsirianni commented
We have been putting source docs at [docs/www/sources](https://github.com/observIQ/bindplane-op/tree/main/docs/www/sources). This may be out of scope for you, I think we should at least track it if we do not implement a doc here. Docs will be published to readme.io during a release.

2022-10-27 20:25 UTC, jsirianni reviewed
I was able to get metrics / logs working with ease :+1:

2022-10-28 00:03 UTC, cpheps commented on resources/source-types/mongodb_atlas.yaml
> +    - name: granularity
Oh cool I didn't know I could do that.

2022-10-28 00:09 UTC, cpheps commented
>We have been putting source docs at [docs/www/sources](https://github.com/observIQ/bindplane-op/tree/main/docs/www/sources). This may be out of scope for you, I think we should at least track it if we do not implement a doc here. Docs will be published to readme.io during a release.

I'm not sure to be honest I didn't know we had docs. How are docs handled for sources that have so much conditional configuration? Do we just list them out best we can?

2022-10-28 13:00 UTC, jsirianni commented
> 

Yeah, there is not a specification on how it is handled right now. A table with each option and an example on how to use the source in its most default form is probably fine.

2022-10-28 14:32 UTC, jsirianni approved these changes

2022-10-31 14:00 UTC, antonblock commented on docs/www/sources/mongodb-atlas.md
> +slug: "mogondb0atlas"
```suggestion
slug: "mongodbatlas"
```
Not sure if that's intentional for the slug

2022-10-31 14:01 UTC, cpheps commented on docs/www/sources/mongodb-atlas.md
> +slug: "mogondb0atlas"
nope fat fingered it.

2022-10-31 14:45 UTC, cpheps commented on docs/www/sources/mongodb-atlas.md
> +slug: "mogondb0atlas"
@antonblock fixed

2022-10-31 14:49 UTC, antonblock approved these changes

2022-10-31 14:49 UTC, merged