feat(UI) add topology to agent page
observIQ/bindplane-op pull request #531
Opened 2022-11-07 14:36 UTC by shazlehu

### Proposed Change
Adds a configuration topology graph to the Agent page.

Resolves observIQ/Iris#1266

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-11-07 14:54 UTC, shazlehu commented
TODO: display measurements for only the selected agent on the configuration graph.

2022-11-08 16:20 UTC, shazlehu commented
Do we like how this is laid out?

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/11639294/200378280-b94c4518-c133-4c32-9946-14fee666f1f8.png">

Current layout:

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/11639294/200378643-092fee71-c65f-4bd2-956a-b986a1716ebd.png">

2022-11-10 15:42 UTC, dsvanlani reviewed
This Editing view is a little weird:

<img width="1638" alt="image" src="https://user-images.githubusercontent.com/64915094/201139834-8167f4e5-176c-4463-b835-bafd0507421f.png">

- The drop down is supposed to be in the bottom box, which should grow to fill the page (I think)
- The top should still read "Configuration - <current_config_name>"
- I dont think we should put the error in the bottom box when editing:
![image](https://user-images.githubusercontent.com/64915094/201144266-e90448ef-da81-4238-ba55-5972c40aaf81.png)

2022-11-10 15:58 UTC, dsvanlani reviewed
I think this is supposed to be the dark blue color: 
![image](https://user-images.githubusercontent.com/64915094/201143829-914ed365-8983-45b5-b962-5cbcdeaa2768.png)

2022-11-10 16:01 UTC, dsvanlani reviewed
Spacing is a little off between the switcher, error, and config 

![image](https://user-images.githubusercontent.com/64915094/201144534-855f4c13-ec53-41c1-9f5a-6a2051e98a63.png)

Should be:

![image](https://user-images.githubusercontent.com/64915094/201144656-5d68cb0e-f905-45e3-b1cc-093c2474f25a.png)

2022-11-10 17:23 UTC, dsvanlani requested changes
Final requests to change:

center details in box
align table rows with no value
remove yaml editor in manageconfig form
Dont display error while editing
Margin below Error Message is too large
Get rid of borderless card container, use box
Remove second box when editing config

2022-11-11 13:57 UTC, shazlehu commented
Implemented all of Dave's changes.

2022-11-14 14:39 UTC, dsvanlani approved these changes
Just need to fix the background color on the new Card, looks clean, working great 👍

2022-11-14 14:39 UTC, dsvanlani commented on ui/src/components/CardContainer/index.tsx
> +      sx={{ borderWidth: 0 }}
This background color should match the app body background.

```suggestion
      sx={{ borderWidth: 0, backgroundColor: "#fcfcfc" }}
```

2022-11-14 16:53 UTC, antonblock commented on ui/src/components/Cards/InlineSourceCard.tsx
> +  //const { configuration, refetchConfiguration } = useConfigurationPage();
```suggestion
```

2022-11-14 16:53 UTC, antonblock commented on ui/src/components/PipelineGraph/ConfigurationFlow.tsx
> +  //const { configuration } = useConfigurationPage();
```suggestion
```

2022-11-14 16:53 UTC, antonblock commented on ui/src/components/PipelineGraph/RawOrTopologyControl.tsx
> +        justifyContent: 'center',
```suggestion
        justifyContent: 'center',
```
There are a few lines in here with a bunch of trailing spaces

2022-11-14 18:58 UTC, antonblock approved these changes
Looks good, minus the small comments I added

2022-11-15 16:55 UTC, merged