Feat/source type/statsd
observIQ/bindplane-op pull request #549
Opened 2022-11-11 21:33 UTC by asenkowski

feat

### Proposed Change
 Added StatsD source type and documentation.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-11-11 21:50 UTC, jsirianni requested changes
This looks good. I added a few description comments.

2022-11-11 21:50 UTC, jsirianni commented on docs/www/sources/statsd.md
> +category: 633dd7654359a20031653089
```suggestion
category: 636c08e1212e49001e7a3032
parentDoc: 636c0a0c46142d00a50b384d
```

This is not merged yet, but you can see the new ID's [here](https://github.com/observIQ/bindplane-op/pull/543/files).

2022-11-11 21:50 UTC, jsirianni commented on docs/www/sources/statsd.md
> +| listen_port | `int` | 8125 | Port to listen on. |
```suggestion
| listen_port | `int` | 8125 | Port to listen on and receive metrics from statsd clients. |
```

2022-11-11 21:50 UTC, jsirianni commented on resources/source-types/statsd.yaml
> +      description: Port to listen on.
```suggestion
      description: Port to listen on and receive metrics from statsd clients.
```

2022-11-11 21:50 UTC, jsirianni commented on docs/www/sources/statsd.md
> +| aggregation_interval | `int` | 60 | The aggregation time in seconds that the receiver aggregates the metrics (similar to the flush interval in StatsD server). |
```suggestion
| aggregation_interval | `int` | 60 | The aggregation time in seconds that the receiver aggregates the metrics. |
```

I think it is okay to keep the last part out.

2022-11-11 21:50 UTC, jsirianni commented on resources/source-types/statsd.yaml
> +      description: The aggregation time in seconds that the receiver aggregates the metrics (similar to the flush interval in StatsD server).
```suggestion
      description: The aggregation time in seconds that the receiver aggregates the metrics.
```

2022-11-11 21:50 UTC, jsirianni commented on resources/source-types/statsd.yaml
> +      description: IP Address to listen on.
```suggestion
      description: IP Address to listen on. Defaults to all addresses.
```

2022-11-15 15:05 UTC, jsirianni approved these changes

2022-11-17 21:14 UTC, antonblock approved these changes
Works well, but I think the two descriptions that repeat the default value can be trimmed

2022-11-17 21:14 UTC, antonblock commented on resources/source-types/statsd.yaml
> +      description: Port to listen on and receive metrics from statsd clients. Defaults to 8125.
I don't think it's necessary to mention the default, since it's visible and documented

2022-11-17 21:14 UTC, antonblock commented on resources/source-types/statsd.yaml
> +      description: IP Address to listen on. Defaults to all addresses.
I don't think it's necessary to mention the default, since it's visible and documented

2022-11-17 22:26 UTC, merged