Document resource types
observIQ/bindplane-op pull request #563
Opened 2022-11-22 22:13 UTC by jsirianni

### Proposed Change

Added the following new docs.
```
docs/dev
└── resource-types.md
    ├── destination-type.md
    ├── processor-type.md
    ├── README.md
    ├── source-type.md
    └── usage.md
```

The goal is to provide details on what resource types are, their possible fields, and how to build or modify a resource type.

These docs are intended for development, therefore they do not exist in `docs/www`, and will not be published to the readme site.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-12-09 14:21 UTC, andykellr commented on docs/dev/resource-types/destination-type.md
> +The `logsz.io` destination type has the following
```suggestion
The `logz.io` destination type has the following
```

2022-12-09 14:25 UTC, andykellr commented on docs/dev/resource-types/README.md
> +| `spec.logs+metrics+traces`       | Defines a special case where generic configuration should be applied to `logs`, `metrics`, and `trace` pipelines. Common with destination types which use a single
Technically there is also `spec.logs+metrics`, `spec.logs+traces`, and `spec.metrics+traces`. The pipelines are always in alphabetical order to limit the combinations (i.e. `spec.traces+logs` is not recognized).

It might be worth describing how these are implementing using gotemplate and linking to the documentation.

2022-12-09 14:28 UTC, andykellr commented on docs/dev/resource-types/usage.md
> +If using the web interface, be sure to refresh your browser before searching for the new source type.
Not sure where exactly it should go, but you should mention that changes to resource types modify configurations that use them and will be pushed to agents immediately.

2022-12-09 14:28 UTC, andykellr requested changes
One typo and a couple suggestions but really nice to have. Nice work.

2023-02-10 17:00 UTC, antonblock approved these changes
Should fix the typo, otherwise awesome

2023-03-09 16:14 UTC, andykellr approved these changes

2023-03-09 19:31 UTC, merged