feat: Rework syslog source to use receiver directly and not the plugin
observIQ/bindplane-op pull request #580
Opened 2022-12-06 21:36 UTC by schmikei

### Proposed Change
Reworks the syslog source to use the [receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/syslogreceiver) directly and exposes more fields for configuration. These fields include:

- enable_octet_counting
- non_transparent_framing_trailer

<details>

<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/32067685/206028184-0828975a-8ebe-4dae-bd05-5f1b3c85e93f.png)
![image](https://user-images.githubusercontent.com/32067685/206028259-895e6f3f-464e-4581-b8e7-02b1da4a63f2.png)

</details>

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-12-07 17:39 UTC, cpheps approved these changes

2022-12-07 19:56 UTC, antonblock requested changes

2022-12-07 19:56 UTC, antonblock commented on resources/source-types/syslog.yaml
> +      relevantIf:
This also needs to check that transport is TCP

2022-12-08 15:49 UTC, schmikei commented on resources/source-types/syslog.yaml
> +      relevantIf:
Pushed 👍

2022-12-09 16:33 UTC, antonblock requested changes

2022-12-09 16:33 UTC, antonblock commented on docs/www/integrations/sources/syslog.md
> +| enable_tls                      | `bool`   | false     | Whether or not to use TLS.
```suggestion
| enable_mutual_tls                      | `bool`   | false     | Whether or not to use mutual TLS.                                                                                                                                                                                     |
```

2022-12-09 17:14 UTC, antonblock approved these changes

2022-12-12 14:39 UTC, merged