feat(ui): Overview page redesign
observIQ/bindplane-op pull request #581
Opened 2022-12-07 18:42 UTC by shazlehu

### Proposed Change

Adds a table of configurations and a table of destinations to the overview page. Nodes are sorted by data in the graph. Selections are saved in the URL search string, so, for example, selecting "Metrics" and "1h" on the overview page will select those on the Configuration page.

Known issues:
-[]  agent count on everything node should respect selected telemetry
-[] destination table needs reload after adding new destination

Resolves observIQ/iris#1332 observIQ/iris#1329 observIQ/iris#1328

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-12-14 16:43 UTC, armstrmi commented on ui/src/components/Cards/OverviewDestinationCard.tsx
> +          </Card>
Were we still planning on keeping this in here? Or replacing it with something else like "data undefined?"

2022-12-14 19:22 UTC, armstrmi commented
Also question, it seems like on default we put all the configurations into the Everything configuration, even if the amount is less than or equal to 3. Likewise with the destination Nodes. 
<img width="1685" alt="image" src="https://user-images.githubusercontent.com/48131175/207693486-6440286a-7d35-4d61-9d63-1b2cbbf0e6ec.png">
However, all else seems fine except for the minor "Hello World" tweak, once all tests are fix/ resolved I'd be happy to approve.

2022-12-20 13:50 UTC, shazlehu commented on ui/src/components/Cards/OverviewDestinationCard.tsx
> +          </Card>
All fixed

2022-12-20 18:11 UTC, dsvanlani requested changes

2022-12-20 18:11 UTC, dsvanlani commented on ui/src/components/PipelineGraph/PipelineGraph.tsx
> +  useEffect(() => {
This useEffect is missing a dependency array, so is doing nothing.

2022-12-20 18:42 UTC, shazlehu commented on internal/graphql/schema.graphqls
> +    configIDs: [ID]
I think you're right.... I feel like I had a reason for it, but now I'm forgetting what it was. Making the change, and testing it out

2022-12-20 18:43 UTC, shazlehu commented on ui/src/components/Tables/ConfigurationTable/ConfigurationsTable.test.tsx
> +  // it("shows delete button after selecting row", async () => {
Indeed, another hacked test I forgot about.

2022-12-20 18:48 UTC, shazlehu commented on internal/graphql/schema.graphqls
> +    period: String!
We just get all the metrics for every telemetry type

2022-12-20 18:50 UTC, shazlehu commented on ui/src/components/PipelineGraph/PipelineGraph.tsx
> +  useEffect(() => {
I believe useEffect will fire once after the render phase if there's no dependency array....

2022-12-20 18:59 UTC, shazlehu commented on internal/graphql/schema.graphqls
> +    configIDs: [ID]
Done.

2022-12-20 19:04 UTC, shazlehu commented on ui/src/components/Cards/OverviewDestinationCard.tsx
> +  enableProcessors?: boolean;
Yup

2022-12-20 19:05 UTC, dsvanlani commented on ui/src/components/PipelineGraph/PipelineGraph.tsx
> +  useEffect(() => {
Ah yes, TIL.

It will run on first mount, but not every render.  This seems appropraite.

2022-12-20 19:06 UTC, shazlehu commented on ui/src/pages/overview/OverviewGraph.tsx
> +      destinationIDs: destinationIDs,
Done

2022-12-20 20:21 UTC, shazlehu commented on ui/src/components/Tables/ConfigurationTable/ConfigurationsDataGrid.tsx
> +      title={`${cellParams.value} (Click to view configuration)`}
The tooltip's main job is to display long names that the table truncates. Maybe only display on the '...' for the truncated name, though that makes it less discoverable? I'm thinking we should leave it as is and make an issue.

2022-12-20 20:25 UTC, shazlehu commented on ui/src/components/Tables/ConfigurationTable/ConfigurationsTable.test.tsx
> +  // it("shows delete button after selecting row", async () => {
I'll make an issue for it

2022-12-20 20:26 UTC, shazlehu commented on ui/src/components/Cards/OverviewDestinationCard.tsx
> +import { useLocation, useNavigate } from "react-router-dom";
I knew you'd get me at least once!

2022-12-20 20:52 UTC, dsvanlani commented on ui/src/components/Tables/ConfigurationTable/ConfigurationsDataGrid.tsx
> +      title={`${cellParams.value} (Click to view configuration)`}
I'm fine with that.

2022-12-20 21:45 UTC, dsvanlani requested changes
A few small things,  working great.

2022-12-20 21:45 UTC, dsvanlani commented on internal/graphql/overview.go
> +	// TODO null check on destinationIDs and configsIDs
```suggestion
```
Dont need this anymore

2022-12-20 21:45 UTC, dsvanlani commented on ui/src/app.tsx
> +
```suggestion
```

2022-12-20 21:45 UTC, dsvanlani commented on ui/src/components/Cards/OverviewDestinationCard.tsx
> +      <div>
I don't think we need this outer div.
```suggestion
```

2022-12-20 21:45 UTC, dsvanlani commented on ui/src/components/Cards/OverviewDestinationCard.tsx
> +        </div>
```suggestion
```

See above.

2022-12-20 21:45 UTC, dsvanlani commented on ui/src/components/PipelineGraph/PipelineGraph.tsx
> +import {
+1

2022-12-20 21:45 UTC, dsvanlani commented on ui/src/utils/state.tsx
> +import { Link, useLocation } from "react-router-dom";
+1

2022-12-20 21:49 UTC, dsvanlani approved these changes
I am good with where this is at - As long as theres an issue for the commented out test.

2023-01-04 19:51 UTC, antonblock requested changes

2023-01-04 19:51 UTC, antonblock commented on ui/src/pages/overview/OverviewPageContext.tsx
> +  // WHY DOESN'T THIS WORK??!?!?!? because of network fetching...
```suggestion
```

2023-01-04 19:51 UTC, antonblock commented on ui/src/utils/state.tsx
> +import { Link, useLocation } from "react-router-dom";
👍

2023-01-04 21:08 UTC, shazlehu commented on internal/graphql/overview.go
> +			activeFlags = activeFlags | configUsage.ActiveFlags()
Agreed, change made

2023-01-04 21:08 UTC, shazlehu commented on internal/graphql/overview.go
> +		period = "1m"
Fixed

2023-01-04 21:09 UTC, shazlehu commented on ui/src/pages/overview/OverviewPageContext.tsx
> +  // WHY DOESN'T THIS WORK??!?!?!? because of network fetching...
Deleted

2023-01-04 21:46 UTC, antonblock reviewed
Need to delete the `screen` and `ConfigurationsTable` imports as well, unused

2023-01-04 21:46 UTC, antonblock commented on ui/src/components/Tables/ConfigurationTable/ConfigurationsTable.test.tsx
> +import { useState } from "react";
```suggestion
```

2023-01-04 21:46 UTC, antonblock commented on ui/src/components/Tables/ConfigurationTable/ConfigurationsTable.test.tsx
> +import { GridSelectionModel } from "@mui/x-data-grid";
```suggestion
```

2023-01-05 14:58 UTC, antonblock approved these changes

2023-01-05 18:16 UTC, merged