added PII mask processor
observIQ/bindplane-op pull request #656
Opened 2023-01-09 17:05 UTC by armstrmi

Signed-off-by: armstrmi <mitchell.armstrong@bluemedora.com>

### Proposed Change

Added PII Processor that wraps [maskprocessor](https://github.com/observIQ/observiq-otel-collector/tree/main/processor/maskprocessor)

##### Checklist
- [x] Changes are tested
- [ ] CI has passed
Data:
```
{
  "email": "mitchell.armstrong@bluemedora.com",
  "email": "abc123._%+-|@abc123.-.hello",
  "email": "hello",
  "phone": "1-616-123-4567",
  "phone": "987978478977987897987",
  "ssn": "123-45-6789",
  "ssn": "123456789",
  "credit_card": "1234-1234-1234-1234",
  "credit_card": "111111111111111",
  "credit_card": "2222222222222222"
}

```
Result:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/48131175/211365371-06ff89b8-dd1d-42a1-9730-420c0dc88570.png">

2023-01-09 19:24 UTC, shazlehu commented on resources/processor-types/filter_pii.yaml
> +  displayName: PII
Was this displayName vetted? If not, I think something more descriptive would be better, e.g. Mask Personal Identifiying Information.

2023-01-09 19:26 UTC, shazlehu commented on resources/processor-types/filter_pii.yaml
> +      description: Expr expression to find matching logs.
There should be a link the Expr language reference here, see "Count Logs" processor

2023-01-09 20:48 UTC, antonblock commented on resources/processor-types/filter_pii.yaml
> +  displayName: PII
+1 to this. I think `Mask Sensitive Data` is a good label

2023-01-09 20:51 UTC, antonblock requested changes

2023-01-09 20:51 UTC, antonblock commented on resources/processor-types/filter_pii.yaml
> +  description: Wraps mask processor to remove PII from log records
```suggestion
  description: Detect and mask sensitive data in log records.
```

2023-01-09 20:52 UTC, jmwilliams89 commented on resources/processor-types/filter_pii.yaml
> +  displayName: PII
I second Nico's suggestion. This processor can be used to mask any type of data. It doesn't have to be personally identifying. So sensitive data is probably more encompassing.

2023-01-09 20:53 UTC, jmwilliams89 commented on resources/processor-types/filter_pii.yaml
> +  displayName: PII
I'd suggesting changing the displayName and name to reflect this. This is also why the underlying processor is called `maskprocessor` because it doesn't have to be PII.

2023-01-09 20:55 UTC, jmwilliams89 commented on resources/processor-types/filter_pii.yaml
> +      description: Expr expression to find matching logs.
This actually isn't using the Expr language. Rules are a series of regex expressions to match on.

2023-01-09 21:23 UTC, shazlehu commented on resources/processor-types/filter_pii.yaml
> +        email: \b[a-z0-9._%\+\-—|]+@[a-z0-9.\-—|]+\.[a-z|]{2,6}\b
'—' character (registers as \U+FFE2) (between the escaped dash and the pipe) looks suspicious to me... Also, I'm pretty sure modern email has a more expansive character set.... Not sure how up to date we want this regexp to be

2023-01-09 21:26 UTC, shazlehu commented on resources/processor-types/filter_pii.yaml
> +        email: \b[a-z0-9._%\+\-—|]+@[a-z0-9.\-—|]+\.[a-z|]{2,6}\b
Also only masks email in lowercase

2023-01-10 15:47 UTC, armstrmi commented on resources/processor-types/filter_pii.yaml
> +        email: \b[a-z0-9._%\+\-—|]+@[a-z0-9.\-—|]+\.[a-z|]{2,6}\b
I agree with lowercase, probably worth while to include those, but I think for the most part we can exclude some of the more fancy characters typically included in spam type emails [!?$%....etc]. However, I do think it would be worthwhile to at least include the uppercase in the regex.

2023-01-17 15:18 UTC, antonblock commented on resources/processor-types/filter_pii.yaml
> +      description: Expr expression to find matching logs.
@armstrmi Should update the description with that ☝️

2023-01-17 15:19 UTC, antonblock commented on resources/processor-types/filter_pii.yaml
> +    - name: rules
This should be required, and then you won't need to check if it's set in the template

2023-01-17 16:41 UTC, antonblock commented on resources/processor-types/filter_pii.yaml
> +  parameters:
Probably also worth adding toggles for enabling on Logs/Metrics/Traces. Check out the custom source type for an example

2023-01-17 18:45 UTC, dehaansa commented on resources/processor-types/filter_pii.yaml
> +      {{ if has "Logs" .telemetry_types }}
It feels cleaner to put this logic around the whole `logs:` section, to not have an empty `logs: processors: |` when logs is not requested. Same for other telemetry types

2023-01-17 22:36 UTC, antonblock approved these changes
Small nitpicks in descriptions, otherwise working well

2023-01-17 22:36 UTC, antonblock commented on resources/processor-types/mask_sensitive_data.yaml
> +  description: Detect and mask sensitive data in log records.
```suggestion
  description: Detect and mask sensitive data in collected telemetry.
```

2023-01-17 22:36 UTC, antonblock commented on resources/processor-types/mask_sensitive_data.yaml
> +      description: "Select which types of telemetry the processor supports."
```suggestion
      description: "Select which types of telemetry to apply masking rules to."
```

2023-01-18 15:10 UTC, merged