feat: Http status code filter processor
observIQ/bindplane-op pull request #659
Opened 2023-01-09 20:29 UTC by Mrod1598

### Proposed Change

Add New processor for filtering based on status code from either the body or the attributes.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-01-09 21:34 UTC, antonblock commented on resources/processor-types/filter_status_code.yaml
> +      label: Status Code Minimum
```suggestion
      label: Minimum Status Code
```

2023-01-09 21:34 UTC, antonblock commented on resources/processor-types/filter_status_code.yaml
> +      label: Status Code Maximum
```suggestion
      label: Maximum Status Code
```

2023-01-09 21:34 UTC, antonblock commented on resources/processor-types/filter_status_code.yaml
> +                  - 'IsMatch(body, "\"?status\"?:({{ $statuses }}),") == true'
I think we may want more flexibility around possible spaces here

2023-01-10 14:58 UTC, Mrod1598 commented on resources/processor-types/filter_status_code.yaml
> +                  - 'IsMatch(body, "\"?status\"?:({{ $statuses }}),") == true'
anywhere specifically?

2023-01-10 15:00 UTC, Mrod1598 commented on resources/processor-types/filter_status_code.yaml
> +      label: Status Code Maximum
Reworked.

2023-01-10 15:00 UTC, Mrod1598 commented on resources/processor-types/filter_status_code.yaml
> +      label: Status Code Minimum
Reworked.

2023-01-17 14:47 UTC, Mrod1598 commented on resources/processor-types/filter_status_code.yaml
> +                  - 'IsMatch(body, "\"?status\"?:({{ $statuses }}),") == true'
updated

2023-01-17 18:19 UTC, antonblock requested changes
Currently getting this error from the collector when using default params

```
invalid syntax; unable to parse OTTL statement: 1:28: invalid quoted string \"\\\"\\\\\\\"?status\\\\\\\"?\\\\s?:\\\\s?(),\\\"\": invalid syntax"
```

2023-01-17 18:19 UTC, antonblock commented on resources/processor-types/filter_status_code.yaml
> +  displayName: HTTP Status Filter
```suggestion
  displayName: Filter By HTTP Status
```

2023-01-17 18:19 UTC, antonblock commented on resources/processor-types/filter_status_code.yaml
> +  description: Filter logs Status Level
```suggestion
  description: Filter logs by whether they contain a HTTP status code in some range.
```

2023-01-17 20:06 UTC, Mrod1598 commented on resources/processor-types/filter_status_code.yaml
> +  displayName: HTTP Status Filter
Updated

2023-01-17 20:06 UTC, Mrod1598 commented on resources/processor-types/filter_status_code.yaml
> +  description: Filter logs Status Level
Updated

2023-01-17 20:08 UTC, Mrod1598 commented
> Currently getting this error from the collector when using default params
> 
> ```
> invalid syntax; unable to parse OTTL statement: 1:28: invalid quoted string \"\\\"\\\\\\\"?status\\\\\\\"?\\\\s?:\\\\s?(),\\\"\": invalid syntax"
> ```

not seeing this error, what version is your collector?

2023-01-18 18:19 UTC, armstrmi commented
I'm seeing something similar to @antonblock 
```
{"level":"error","ts":"2023-01-18T13:18:33.047-0500","logger":"opamp","caller":"observiq/observiq_client.go:325","msg":"Failed applying remote config","error":"failed to reload config: collector.yaml: collector failed to restart: invalid configuration: processor \"filter/source1__processor0\" has invalid configuration: 1:34: invalid quoted string \"\\\"\\\\\\\"?status\\\\\\\"?\\\\s?:\\\\s?(),\\\"\": invalid syntax; 1:28: invalid quoted string \"\\\"\\\\\\\"?status\\\\\\\"?\\\\s?:\\\\s?(),\\\"\": invalid syntax",
```

2023-01-18 18:46 UTC, armstrmi commented on resources/processor-types/filter_status_code.yaml
> +                    {{ if (not (and (le .minimum "100") (ge .maximum "200"))) }}
I might be a little confused by the logic here and misunderstand how it is chosen, but would you want to include 100 level codes in the case that minimum is less than or equal to 100 and maximum is greater than or equal to 200? This statement seems to only accept in the case that mimum and maximum both == 100

2023-01-18 19:00 UTC, armstrmi commented on resources/processor-types/filter_status_code.yaml
> +                    {{ if (not (and (le .minimum "100") (ge .maximum "200"))) }}
Also, I have updated collector version to latest, and still seeing that syntax error with the quotations.

2023-01-18 19:04 UTC, Mrod1598 commented on resources/processor-types/filter_status_code.yaml
> +                    {{ end }}
Pretty sure there aren't 600 level status codes, this is more just to say every thing below 600
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2023-01-18 19:08 UTC, armstrmi commented on resources/processor-types/filter_status_code.yaml
> +                    {{ end }}
Ok, so in that case, should the valid values only be up to 500 instead and possibly tweak those. Because in the description it says "Highest possible status code to allow through" which seems like 600 would be a valid status code.

2023-01-18 19:19 UTC, Mrod1598 commented on resources/processor-types/filter_status_code.yaml
> +                    {{ $statuses := "" }}
not sure if we really have a mechanism for throwing errors.

2023-01-18 19:20 UTC, Mrod1598 commented on resources/processor-types/filter_status_code.yaml
> +                    {{ if (not (and (le .minimum "100") (ge .maximum "200"))) }}
It adds it statuses when appropriate if a little confusing with templating logic, fixed it though so play with it and you'll see what it looks like.

2023-01-19 14:21 UTC, armstrmi approved these changes

2023-01-19 14:21 UTC, armstrmi commented on resources/processor-types/filter_status_code.yaml
> +                  - 'IsMatch(body, "\"?status\"? ?: ?({{ $statuses }}),") == true'
nit: new line character

2023-01-19 14:53 UTC, antonblock approved these changes
Looks good, statuses are filtered correctly and logs without status aren't touched

2023-01-19 15:11 UTC, merged