feat(topology): Show all telemetry on config topology
observIQ/bindplane-op pull request #669
Opened 2023-01-17 18:06 UTC by antonblock

### Proposed Change

- Update `PipelineGraph` to show all telemetry types at once
- Add alternate `updateMetricData` function to fetch and format that

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-01-24 19:40 UTC, andykellr commented on ui/src/components/PipelineGraph/Nodes/CustomEdge.tsx
> +import 'reactflow/dist/style.css';
Noticed the quote style changed above from single to double and now this is single. Should we add this to the linter?

2023-01-24 19:42 UTC, antonblock commented on ui/src/components/PipelineGraph/Nodes/CustomEdge.tsx
> +import 'reactflow/dist/style.css';
Good catch. Yeah the presets we use don't seem to care, I'm in favor of enforcing double quotes

2023-01-24 19:46 UTC, andykellr approved these changes
Working well and the code looks clean. One question about single vs double quotes.

<img width="1616" alt="Screenshot 2023-01-24 at 2 28 12 PM" src="https://user-images.githubusercontent.com/2660251/214392967-48bb3b95-e31a-4505-875a-390e4006f884.png">

Also, I don't love the metric label format (too bold?, remove colons?) but I assume this matches the design.

2023-01-24 22:03 UTC, andykellr requested changes
Labels always in center, processor spacing inconsistent.

2023-01-25 16:12 UTC, dsvanlani commented on ui/src/components/PipelineGraph/Nodes/CustomEdge.tsx
> +import 'reactflow/dist/style.css';
+1

2023-01-25 16:27 UTC, dsvanlani reviewed
I think we should dim telemetry labels as part of the hover functionality:

![image](https://user-images.githubusercontent.com/64915094/214619465-7798fd07-bcff-42a9-8b2a-a8d0d7675655.png)

2023-01-25 16:36 UTC, dsvanlani commented on ui/src/components/MeasurementControlBar/MeasurementControlBar.tsx
> +  telemetryTypes = TELEMETRY_TYPES,
I'd prefer to not set a default here, and just conditionally render the telemetry types if present.  

This makes it so you don't have to pass an empty object `{ }` into the MeasurementControlBar, just not passing telemetry types is sufficient.  Then in the OverviewGraph we can more explicitly pass in the telemetry types.  

I

2023-01-25 16:42 UTC, dsvanlani commented on ui/src/components/PipelineGraph/Edges/ConfigurationEdge.tsx
> +import { Stack } from "@mui/material";
Theres two files called ConfigurationEdge now.  Can we rename one? Probably this one to `CustomEdge.tsx` ?

2023-01-25 16:55 UTC, dsvanlani requested changes
This is looking good.  It looks like the labels should be dimmed on hover but I didn't look into too much why they were not dimming.  It looks like we have access to that hovered set so I think it would be good to get in.

2023-01-25 16:55 UTC, dsvanlani commented on ui/src/components/PipelineGraph/Edges/ConfigurationEdge.tsx
> +            position: "absolute",
Ahh, I see we have to set the translate programmatically.

I'm okay with this for now.

2023-02-09 16:28 UTC, dsvanlani approved these changes

2023-02-09 19:08 UTC, shazlehu commented on ui/src/utils/graph/utils.ts
> +/**
Gold star for finally commenting this beast!

2023-02-09 20:15 UTC, shazlehu approved these changes
Looks really nice, and again, thanks for adding sorely needed comments.

2023-03-22 17:13 UTC, closed without merging