fix(ui): Hides pagination on overview page
observIQ/bindplane-op pull request #670
Opened 2023-01-17 21:35 UTC by shazlehu

### Proposed Change

Hides pagination on the Overview page using canonical React instead of wildwest-style DOM manipulation.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-01-18 14:37 UTC, dsvanlani requested changes
1. I think the fetch policy for both overview and destinations page should be `network-only`.
2. Instead of passing in a boolean prop - lets just have `ConfigurationTable` and `DestinationTable` take in classes of type `DataGridProps["classes"]`, That way we don't have to pass in page-specific props to the `DataGrid` component.

2023-01-18 17:05 UTC, dsvanlani approved these changes

2023-01-18 19:31 UTC, shazlehu commented on ui/src/components/Tables/ConfigurationTable/index.tsx
> +      fetchPolicy: overviewPage
This resolved a caching issue when we built overview page.

2023-01-18 19:32 UTC, shazlehu commented on ui/src/components/Tables/DestinationsTable/DestinationsDataGrid.tsx
> +        classes={destinationsPage ? {} :  {footerContainer:  mixins["hidden"]}}
Yup, fixed

2023-01-18 19:33 UTC, shazlehu commented on ui/src/components/Tables/ConfigurationTable/ConfigurationsDataGrid.tsx
> +
Causes the tables to push beyond the bounds of their containers instead of enabling the scroll bar

2023-01-19 19:53 UTC, antonblock approved these changes
Working great, added a comment to simplify the type check in `DestinationsPage`

2023-01-19 19:53 UTC, antonblock commented on ui/src/pages/destinations/DestinationsPage.tsx
> +        : [...(queryData as DestinationsInConfigsQuery).destinationsInConfigs];
```suggestion
    const rows = "destinations" in queryData
        ? [...queryData.destinations]
        : [...queryData.destinationsInConfigs];
```

I think this can be a bit cleaner using a type guard, either way `const rows` is indented too far

2023-01-19 21:37 UTC, merged