fix(ui): Gracefully shrink and truncate long names
observIQ/bindplane-op pull request #676
Opened 2023-01-18 18:58 UTC by shazlehu

### Proposed Change

Truncates long names with ellipsis and shrinks font for names longer than 15 characters. Adds a tool tip to display the full name for truncated names.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-01-19 14:55 UTC, Mrod1598 approved these changes
<img width="317" alt="image" src="https://user-images.githubusercontent.com/14144136/213474727-fb91258e-0001-45da-b0a6-c3aefdaf9509.png"> 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/14144136/213474831-94924238-d9ba-4479-a2f2-3e262fd05eed.png">
LGTM

2023-01-19 18:45 UTC, dsvanlani requested changes

2023-01-19 18:45 UTC, dsvanlani commented on ui/src/components/Cards/OverviewDestinationCard.tsx
> +                    {cardName.length > 20 && !cardName.includes(" ")
Looks like we do this a couple places, can we factor this out into a function in `ui/src/utils` ?

2023-01-19 19:16 UTC, shazlehu commented on ui/src/components/Cards/OverviewDestinationCard.tsx
> +                    {cardName.length > 20 && !cardName.includes(" ")
Surely

2023-01-20 14:48 UTC, dsvanlani approved these changes
Working great!

2023-01-20 16:06 UTC, merged