feat(tracing): Implement Open Telemetry collector tracing exporter
observIQ/bindplane-op pull request #70
Opened 2022-07-07 22:17 UTC by jsirianni

### Proposed Change

- Refactored tracing to support multiple providers
- Created package `internal/trace` for building and returning trace providers
- Implemented OTLP (via gRPC) trace provider

Right now, the OTLP provider works with plain text connections only, but can be enhanced to support tls, mtls, etc.

Tested against Google Cloud and observiq-otel-collector w/ Jaeger exporter. I verified that BindPlane shuts down cleanly with both providers.

![Screenshot from 2022-07-07 18-10-32](https://user-images.githubusercontent.com/23043836/177880102-0650b1a0-c8dd-4e59-835b-83de6ce7bf42.png)

You can test with:

```bash
docker run -p 16686:16686 -p 14250:14250 jaegertracing/all-in-one
```

Run a collector with the following config
```yaml
receivers:
    otlp/otlp__source0:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318
exporters:
    logging/logging__debug:
        logLevel: info

    jaeger:
      endpoint: localhost:14250
      tls:
        insecure: true
service:
    pipelines:
        logs/otlp__source0__debug:
            receivers:
                - otlp/otlp__source0
            processors: []
            exporters:
                - logging/logging__debug
        metrics/otlp__source0__debug:
            receivers:
                - otlp/otlp__source0
            processors: []
            exporters:
                - logging/logging__debug
        traces/otlp__source0__debug:
            receivers:
                - otlp/otlp__source0
            processors: []
            exporters:
                - logging/logging__debug
                - jaeger
```

And use the following iris config
```yaml
...
server:
    traceType: otlp
    otlpTracing:
      endpoint: localhost:4317
      tls:
        insecure: true
...
```

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-07-08 16:41 UTC, andykellr commented on internal/cli/commands/root.go
> +		bindplane.Logger().Info("flushing traces before shutdown")
Is flushing still needed? I don't see it happening.

2022-07-08 17:03 UTC, jsirianni commented on internal/cli/commands/root.go
> +		bindplane.Logger().Info("flushing traces before shutdown")
I think the hook should be canceling the context. I moved the context creation outside of the hook because it is needed when creating the otlp exporter (and is now being passed into the google exporter creation function).

Line 223 calls `cancel()`.

2022-07-08 20:28 UTC, jsirianni commented on internal/cli/commands/root.go
> +		bindplane.Logger().Info("flushing traces before shutdown")
I understand. We still need to call tp.Shutdown, I will add that.

2022-08-08 19:54 UTC, andykellr requested changes
This is a nice improvement, but we still need to implement Shutdown I think.

2022-08-10 18:17 UTC, jsirianni commented
@andykellr I switched back to the original shutdown hook, it should work fine for both trace options.

Jaeger now has native OTLP ingestion, so you do not need a collector to test:

```bash
docker run --name jaeger \
  -e COLLECTOR_OTLP_ENABLED=true \
  -p 16686:16686 \
  -p 4317:4317 \
  -p 4318:4318 \
  jaegertracing/all-in-one:1.35
```

Web ui is at http://localhost:16686/

My bindplane config looks like this 

```yaml
host: 0.0.0.0
port: "3001"
serverURL: http://127.0.0.1:3001
username: redacted
password: redacted
server:
    secretKey: redacted
    remoteURL: ws://127.0.0.1:3001
    sessionsSecret: redacted
    traceType: otlp
    #traceType: google
    googleTracing:
      projectID: redacted
      credentialsFile: /tmp/creds.json
    otlpTracing:
      endpoint: localhost:4317
      tls:
        insecure: true
```

<img width="1483" alt="Screen Shot 2022-08-10 at 2 13 04 PM" src="https://user-images.githubusercontent.com/23043836/183986273-902f2a96-1ef6-4e27-8adb-0b94212a5a6f.png">

<img width="1477" alt="Screen Shot 2022-08-10 at 2 13 18 PM" src="https://user-images.githubusercontent.com/23043836/183986305-d9807d27-e96c-4eb1-afde-801e828418a1.png">

2022-08-19 01:09 UTC, andykellr approved these changes
Worked great for me.

I used this command as suggested at https://www.jaegertracing.io/docs/1.37/getting-started/

```sh
docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
  -e COLLECTOR_OTLP_ENABLED=true \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 4317:4317 \
  -p 4318:4318 \
  -p 14250:14250 \
  -p 14268:14268 \
  -p 14269:14269 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.37
```

with the changes you suggested to my profile yaml, e.g. 


```yaml
server:
    traceType: otlp
    otlpTracing:
      endpoint: localhost:4317
      tls:
        insecure: true
```

2022-08-19 02:26 UTC, merged