feat(processor): add Aggregate Metrics processor
observIQ/bindplane-op pull request #740
Opened 2023-02-15 16:47 UTC by BinaryFissionGames

### Proposed Change
* Adds the Aggregate Metrics processor, which can be used to aggregate metrics over a fixed time interval.

![aggregate_metrics_avg_min_max](https://user-images.githubusercontent.com/10042942/219096049-b9438852-fd5e-4869-b2d2-a1016ffd5b91.png)

##### Checklist
- [x] Changes are tested
- [ ] CI has passed

2023-02-15 18:22 UTC, cpheps approved these changes
LGTM tested it and seemed to work just fine.

2023-02-15 20:39 UTC, jsirianni approved these changes
Working great for me. I was able to read bindplane's log file, convert body.latency to a metric and then use this new processor to aggregate the latency metric.

2023-02-15 21:55 UTC, dsvanlani requested changes

2023-02-15 21:55 UTC, dsvanlani commented on ui/src/components/ResourceConfigForm/ParameterInput/AggregationDefinitionInput.tsx
> +                  name: "type_" + index,
I guess it doesn't really matter here but this would be `ParameterType.Enum`

2023-02-15 21:55 UTC, dsvanlani commented on ui/src/components/ResourceConfigForm/ParameterInput/AggregationDefinitionInput.tsx
> +  function addNewField() {
I think you want to have the default so the UI state doesn't look weird.
```
type: "Minimum Value"
``

2023-02-15 22:47 UTC, dsvanlani approved these changes

2023-02-17 17:06 UTC, cpheps approved these changes

2023-02-17 17:55 UTC, dsvanlani approved these changes
Working great.  Not sure if we want to wait on merging until the collector with the change is released.

2023-02-20 19:18 UTC, jsirianni approved these changes

2023-02-23 16:13 UTC, merged