fix(measurements): Show log-based metrics after source processor
observIQ/bindplane-op pull request #761
Opened 2023-02-20 19:47 UTC by antonblock

### Proposed Change

In `updateMetricData`, assign metrics created by log-based metrics processors to that source's processor. So instead of only displaying at d0, also display at s1.

- Add tests
- Add comments

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-02-22 15:54 UTC, andykellr commented on ui/src/utils/graph/utils.ts
> +  ) ?? findRouteReceiverMetric(nodeID, metrics, telemetryType);
Instead of only looking for the route receiver metric if there is no node metric, we should always look for it and add it in. That way if the source produces metrics and logs and we add a log count processor, the count metrics are added to the existing metrics produced by the source.

2023-02-22 15:54 UTC, andykellr requested changes
It should add source metric throughput and processor metric throughput to produce a total.

2023-02-28 13:50 UTC, Mrod1598 approved these changes

2023-02-28 15:31 UTC, dsvanlani approved these changes

2023-02-28 18:36 UTC, merged