feat(sourcetype): Add a W3C source type
observIQ/bindplane-op pull request #821
Opened 2023-03-07 16:03 UTC by BinaryFissionGames

### Proposed Change
* Adds a W3C source type based on the collector plugin.

This source type requires the next release of the collector, v1.20.0, because it relies on new parameters added to the W3C plugin.

##### Checklist
- [x] Changes are tested
- [ ] CI has passed

2023-03-07 17:09 UTC, cpheps requested changes
I got this error when configuring a default source only specifying the file path

```
Failed to apply config changes: failed to reload config: collector.yaml: collector failed to restart: failed to build pipelines: failed to create "plugin/source0" receiver, in pipeline "logs/*": invalid plugin parameter: definition failure: parameter header_delimiter is not defined in plugin
```

2023-03-07 17:09 UTC, cpheps commented on resources/source-types/w3c.yaml
> +      default: "\t"
This shows up as a blank space until you click in the box. It's not clear to me what the delimter is.

2023-03-07 17:10 UTC, cpheps commented
@BinaryFissionGames oh wait I forgot I had to build from the current release branch let me change that.

2023-03-07 17:16 UTC, cpheps reviewed
This does work but I do think we need to find some way to convey the tab character better if possible.

2023-03-07 18:01 UTC, BinaryFissionGames commented
@cpheps Updated to use an enum instead of a raw string for delimiters.

2023-03-07 18:01 UTC, cpheps approved these changes

2023-03-07 22:34 UTC, jsirianni reviewed
Getting this error with the latest build of the collector (main branch)
```
Failed to apply config changes: failed to reload config: 
collector.yaml: collector failed to restart: 
failed to build pipelines: failed to create "plugin/source0" receiver, in pipeline "logs/*": 
invalid plugin parameter: 
required failure: 
parameter header is missing but required in plugin
```

2023-03-07 22:34 UTC, jsirianni commented on resources/source-types/w3c.yaml
> +          parameters:
Can we add the start_at option?

2023-03-07 22:37 UTC, BinaryFissionGames commented on resources/source-types/w3c.yaml
> +          parameters:
`start_at` can only be `beginning` for automatic header parsing to work, so I've left it out since the automatic header parsing is the only allowed configuration.

2023-03-07 22:38 UTC, BinaryFissionGames commented
> Getting this error with the latest build of the collector (main branch)
> 
> ```
> Failed to apply config changes: failed to reload config: 
> collector.yaml: collector failed to restart: 
> failed to build pipelines: failed to create "plugin/source0" receiver, in pipeline "logs/*": 
> invalid plugin parameter: 
> required failure: 
> parameter header is missing but required in plugin
> ```

We've started merging into release branches on the collector side, so main isn't up-to-date just yet. It should work if you try a build from the release branch: https://github.com/observIQ/observiq-otel-collector/tree/release/v1.20.0

2023-03-08 14:11 UTC, jsirianni approved these changes
Working great for me. Unrelated to this PR, I did notice that the plugin is parsing to attributes, we may want it to go to body. 

```
ResourceLog #0
Resource SchemaURL: https://opentelemetry.io/schemas/1.6.1
Resource attributes:
-> host.name: Str(fedora)
-> os.type: Str(linux)
-> host.id: Str(5778867c5ec44754bc187a6bd5c5485c)
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 2023-03-08 14:06:52.98258716 +0000 UTC
Timestamp: 1970-01-01 00:00:00 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Str(2020-11-03 16:13:15 10.33.104.51 GET / - 80 - 10.33.121.100 Go-http-client/1.1 - 200 0 0 67)
Attributes:
-> s-ip: Str(10.33.104.51)
-> date: Str(2020-11-03)
-> time-taken: Str(67)
-> log_type: Str(w3c)
-> log.file.name: Str(iis.log)
-> s-port: Str(80)
-> cs(User-Agent): Str(Go-http-client/1.1)
-> sc-substatus: Str(0)
-> time: Str(16:13:15)
-> cs-method: Str(GET)
-> c-ip: Str(10.33.121.100)
-> cs-username: Str(-)
-> sc-win32-status: Str(0)
-> cs(Referer): Str(-)
-> sc-status: Str(200)
-> cs-uri-stem: Str(/)
-> cs-uri-query: Str(-)
```

2023-03-08 14:12 UTC, cpheps commented
> Unrelated to this PR, I did notice that the plugin is parsing to attributes, we may want it to go to body.

@jsirianni We only updated the plugins that are most used. If this one becomes popular we may want to make the change. Currently most plugins still parse to attributes.

2023-03-08 14:16 UTC, merged