feat(sourcetype): Add Sap Netweaver source type
observIQ/bindplane-op pull request #825
Opened 2023-03-07 20:31 UTC by JonathanWamsley

### Proposed Change

Adds SAP Netweaver source type based on the collector plugin.

SAP Netweaver Source in Add Source modal:
![SAP Netweaver Source Type](https://user-images.githubusercontent.com/13648435/223535339-c36868b4-0345-43d3-bcf8-6b859bb3c807.png)

SAP Netweaver Source Config:
![SAP Netweaver Source Config](https://user-images.githubusercontent.com/13648435/223535809-f25e0388-546b-4933-948e-18859801139b.png)

![SAP Netweaver Source Config 2](https://user-images.githubusercontent.com/13648435/223536023-414deead-443b-4a7d-b96c-8706c4a518ff.png)

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-03-07 22:12 UTC, jsirianni requested changes

2023-03-07 22:12 UTC, jsirianni commented on docs/www/integrations/sources/sap-netweaver.md
> +---
We are no longer contributing docs to the repo. Team will review this and then remove it before merging. We will also handle porting it into readme.io.

2023-03-07 22:12 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +    - linux
Can the collector run remotely / from a different system than the SAP system? If so, I think we can support linux, windows, and macos here.

2023-03-07 22:12 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +    # Metrics
Because this is a metrics only source type (does not support logs / trace), we can remove the `enable_metrics` logic.

2023-03-07 22:12 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +      description: The profile path in the form of /sapmnt/SID/profile/SID_INSTANCE_HOSTNAME to collect sapnetweaver.abap.rfc.count and sapnetweaver.abap.session.count metrics.
Is this a file on the SAP system? If so, it probably means the collector must run on the SAP system directly? If so, ignore my first comment on supported platforms.

We still might support Windows, as SAP Netweaver does have a windows option AFAIK.

2023-03-07 22:12 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +      advancedConfig: true
If profile is optional, I think we should mention what it enables when used, and possibly link to external documentation if you think that would be useful.

```suggestion
      advancedConfig: true
      documentation:
        - text: Read more
          url: https://linktodoc.com/somepath
```

2023-03-07 22:12 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +          password: {{ .password }}
Sometimes fields like this can behave funny if not wrapped in single quotes.

```suggestion
          username: '{{ .username }}'
          password: '{{ .password }}'
```

2023-03-07 22:12 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +            profile: {{ .profile }}
```suggestion
            profile: '{{ .profile }}'
```

2023-03-07 22:12 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +            profile: {{ .profile }}
No need to indent here
```suggestion
          {{ if .profile }}
          profile: {{ .profile }}
```

2023-03-08 18:36 UTC, JonathanWamsley commented on docs/www/integrations/sources/sap-netweaver.md
> +---
removed

2023-03-08 18:36 UTC, JonathanWamsley commented on resources/source-types/sap_netweaver.yaml
> +    - linux
ignored as stated below

2023-03-08 18:36 UTC, JonathanWamsley commented on resources/source-types/sap_netweaver.yaml
> +    # Metrics
updated

2023-03-08 18:37 UTC, JonathanWamsley commented on resources/source-types/sap_netweaver.yaml
> +      description: The profile path in the form of /sapmnt/SID/profile/SID_INSTANCE_HOSTNAME to collect sapnetweaver.abap.rfc.count and sapnetweaver.abap.session.count metrics.
I asked Project manager Joe, and he said to just support linux unless we hear otherwise

2023-03-08 18:37 UTC, JonathanWamsley commented on resources/source-types/sap_netweaver.yaml
> +      advancedConfig: true
add docs. It is a little confusing because the [reference docs](https://help.sap.com/docs/SAP_NETWEAVER_750/b17bd20044a44edb9aa7830ee52ffac3/00fabccaa98348f291f3c7f02098116b.html) show the base path to be `/usr/sap/<SID>/SYS/profile` however when investigating and talking to SAP experts, we used `/sapmnt/SID/profile` which [are basically the same thing](https://answers.sap.com/answers/5487635/view.html) and is softlink there

2023-03-08 18:37 UTC, JonathanWamsley commented on resources/source-types/sap_netweaver.yaml
> +          password: {{ .password }}
updated

2023-03-08 18:37 UTC, JonathanWamsley commented on resources/source-types/sap_netweaver.yaml
> +            profile: {{ .profile }}
updated

2023-03-08 18:37 UTC, JonathanWamsley commented on resources/source-types/sap_netweaver.yaml
> +            profile: {{ .profile }}
updated

2023-03-09 20:37 UTC, jsirianni requested changes
I am having some issues due to the protocol not being injected into the `endpoint` parameter. See comments.

2023-03-09 20:37 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +      advancedConfig: true
Lets remove `advancedConfig` from these, as they are required options and should be front and center.

2023-03-09 20:37 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +          endpoint: {{ .hostname }}:{{ .port }}
I think this is missing the protocol. Lets do `https` if enable_tls is true, else `http`.

2023-03-09 20:37 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +            insecure: false
We [recently discovered](https://github.com/observIQ/bindplane-op/pull/829) that tls.insecure is gRPC specific, and is not required if using the otel http client.

2023-03-09 20:37 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +          {{ end }}
See previous comment

```suggestion
          {{ end }}
```

2023-03-09 21:39 UTC, JonathanWamsley commented on resources/source-types/sap_netweaver.yaml
> +      advancedConfig: true
removed

2023-03-09 21:39 UTC, JonathanWamsley commented on resources/source-types/sap_netweaver.yaml
> +          endpoint: {{ .hostname }}:{{ .port }}
added protocol but for .configure_tls instead

2023-03-09 21:39 UTC, JonathanWamsley commented on resources/source-types/sap_netweaver.yaml
> +            insecure: false
applied similar changes

2023-03-09 21:39 UTC, JonathanWamsley commented on resources/source-types/sap_netweaver.yaml
> +          {{ end }}
updated

2023-03-09 21:50 UTC, jsirianni commented on resources/source-types/sap_netweaver.yaml
> +          endpoint: {{ .hostname }}:{{ .port }}
I think `enable_tls` is fine, because it does indicate whether TLS is going to be used or not.

The Loki resource is different because we rely on the user to specify the protocol (Loki's endpoint parameter is a full URL).

The logic in the template looks good though, I just think we can revert back to enable_tls.

2023-03-09 22:32 UTC, jsirianni approved these changes

2023-03-09 22:32 UTC, jsirianni commented
Looking good

![Screenshot from 2023-03-09 17-30-39](https://user-images.githubusercontent.com/23043836/224175288-6b01853d-781e-4d15-8999-805250026363.png)

2023-03-10 13:11 UTC, jmwilliams89 approved these changes

2023-03-10 14:29 UTC, jsirianni approved these changes

2023-03-10 14:50 UTC, merged