feat: Grafana Cloud Destination Use OTLP
observIQ/bindplane-op pull request #888
Opened 2023-03-24 17:20 UTC by cpheps

### Proposed Change
Changed the Grafana Cloud Destination to use OTLP.

It now supports all telemetry types.

**NOTE:** Requires collector v1.21.1 or greater as we added the `basicauth` extension in that collector version.

Example of dashboard showing OTLP metrics and logs:

![Screenshot 2023-03-24 at 1 16 27 PM](https://user-images.githubusercontent.com/11877763/227596087-76fddae9-a4b1-4150-b8df-8ac03fbb771d.png)

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2023-03-24 18:49 UTC, dsvanlani requested changes
Everythings working great - but I think its annoying to have to create the endpoint yourself,  I think we should have a `Zone` parameter and make this url for the user.

i.e
```yaml 
name: gcp_zone
label: Zone
description: The GCP region associated with your Grafana Cloud instance.
type: enum
options:
    createable: true
validValues: 
    - prod-au-southeast-0
    - prod-eu-west-0
    - prod-sa-east-0
    - prod-ap-sout-0
    - prod-ap-southeast-0
    - prod-gb-south-0
    - prod-us-central-0
```

then in the template:

```yaml
endpoint: https://otlp-gateway-{{ .gcp_zone}}.grafana.net/otlp
```

2023-03-24 19:39 UTC, jsirianni commented
> Everythings working great - but I think its annoying to have to create the endpoint yourself, I think we should have a `Zone` parameter and make this url for the user.
> 
> i.e
> 
> ```yaml
> name: gcp_zone
> label: Zone
> description: The GCP region associated with your Grafana Cloud instance.
> type: enum
> options:
>     createable: true
> validValues: 
>     - prod-au-southeast-0
>     - prod-eu-west-0
>     - prod-sa-east-0
>     - prod-ap-sout-0
>     - prod-ap-southeast-0
>     - prod-gb-south-0
>     - prod-us-central-0
> ```
> 
> then in the template:
> 
> ```yaml
> endpoint: https://otlp-gateway-{{ .gcp_zone}}.grafana.net/otlp
> ```

I agree, considering the rest of the endpoint is always the same.

2023-03-27 12:12 UTC, cpheps commented
@jsirianni @dsvanlani I'm fine with that but I wanted to ask a quick question about backwards compatibility as currently the new solution is backwards compatible where changing endpoint to zone I don't think would be. I'm not sure how breaking changes work in destinations.

2023-03-27 14:08 UTC, jsirianni requested changes

2023-03-27 15:05 UTC, cpheps commented on resources/destination-types/grafana_cloud.yaml
> +  logs+metrics+traces:
Talked this over offline. Because there's an `extension`, `exporter`, and `processor` having telemetry toggles doesn't seem like the ideal solution. Ideally what we want is to just omit this exporter from a pipeline not redeclare it for each pipeline.

2023-03-27 15:32 UTC, jsirianni approved these changes

2023-03-27 16:12 UTC, merged